// 12 week plans: B=breakfast R=refuel L=lunch D=dinner
// batch slot = [recipeId, batchFromDay]
[
{cycle:1,week:1,days:[
  {day:"mon",B:"coconutOvernightOats",R:"butternutSquashRisotto",D:"thaiRedVegCurry",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["coconutOvernightOats","mon"],R:["butternutSquashRisotto","mon"],D:["thaiRedVegCurry","mon"],snacks:"Rice cakes + almond butter · Banana"},
  {day:"wed",B:"pbJamSmoothie",L:"quinoaEdamameSalad",D:"almondPestoPasta",snacks:"Trail mix · Orange"},
  {day:"thu",B:"bananaCoconutSmoothie",R:"oatmealRaisinSmoothie",D:"spicyTofuAsianSlaw",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["bananaCoconutSmoothie","thu"],R:"overnightOatsProtein",D:["spicyTofuAsianSlaw","thu"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"charredCornSalad",D:"spicyMushroomLettuceCups",snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"moroccanChickpeaStew",D:"sichuanAubergine",snacks:"Trail mix · Banana"},
]},
{cycle:1,week:2,days:[
  {day:"mon",B:"pbJamSmoothie",R:"aaalooGobi",D:"saagTofu",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["pbJamSmoothie","mon"],R:["aaalooGobi","mon"],D:["saagTofu","mon"],snacks:"Banana · Veg batons + hummus"},
  {day:"wed",B:"bananaCoconutSmoothie",L:"tuscanBeanStew",D:"spicyMushroomLettuceCups",snacks:"Trail mix · Orange"},
  {day:"thu",B:"coconutOvernightOats",R:"butternutSquashRisotto",D:"moroccanChickpeaStew",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["coconutOvernightOats","thu"],R:["butternutSquashRisotto","thu"],D:["moroccanChickpeaStew","thu"],snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"quinoaEdamameSalad",D:"almondPestoPasta",snacks:"Trail mix · Fresh fruit"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"charredCornSalad",D:"thaiRedVegCurry",snacks:"Mixed nuts · Banana"},
]},
{cycle:1,week:3,days:[
  {day:"mon",B:"bananaCoconutSmoothie",R:"oatmealRaisinSmoothie",D:"spicyTofuAsianSlaw",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["bananaCoconutSmoothie","mon"],R:["oatmealRaisinSmoothie","mon"],D:["spicyTofuAsianSlaw","mon"],snacks:"Banana · Trail mix"},
  {day:"wed",B:"coconutChiaPudding",L:"charredCornSalad",D:"saagTofu",snacks:"Trail mix · Orange"},
  {day:"thu",B:"pbJamSmoothie",R:"aaalooGobi",D:"thaiRedVegCurry",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["pbJamSmoothie","thu"],R:"overnightOatsProtein",D:["thaiRedVegCurry","thu"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"sat",B:"coconutOvernightOats",L:"quinoaEdamameSalad",D:"almondPestoPasta",snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sun",B:["coconutOvernightOats","sat"],L:"tuscanBeanStew",D:"moroccanChickpeaStew",snacks:"Trail mix · Banana"},
]},
{cycle:1,week:4,days:[
  {day:"mon",B:"coconutChiaPudding",R:"overnightOatsProtein",D:"sichuanAubergine",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["coconutChiaPudding","mon"],R:["overnightOatsProtein","mon"],D:["sichuanAubergine","mon"],snacks:"Banana · Veg batons + hummus"},
  {day:"wed",B:"pbJamSmoothie",L:"moroccanChickpeaStew",D:"spicyMushroomLettuceCups",snacks:"Trail mix · Orange"},
  {day:"thu",B:"bananaCoconutSmoothie",R:"butternutSquashRisotto",D:"saagTofu",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["bananaCoconutSmoothie","thu"],R:"aaalooGobi",D:["saagTofu","thu"],snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sat",B:"coconutOvernightOats",L:"charredCornSalad",D:"thaiRedVegCurry",snacks:"Trail mix · Fresh fruit"},
  {day:"sun",B:["coconutOvernightOats","sat"],L:"spicyTofuAsianSlaw",D:"quinoaEdamameSalad",snacks:"Mixed nuts · Banana"},
]},
{cycle:2,week:1,days:[
  {day:"mon",B:"spicedBerryPorridge",R:"roastedVegQuinoa",D:"thaiCarrotSoup",snacks:"Mixed nuts · Rice cakes + almond butter"},
  {day:"tue",B:["spicedBerryPorridge","mon"],R:["roastedVegQuinoa","mon"],D:["thaiCarrotSoup","mon"],snacks:"Banana · Veg batons + hummus"},
  {day:"wed",B:"gogoGreenSmoothie",L:"splitPeaSpinachSoup",D:"creamyTomatoPasta",snacks:"Trail mix · Fresh fruit"},
  {day:"thu",B:"carrotCakeSmoothie",R:"mixedBeanChilli",D:"mushroomGingerCashewStirFry",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["carrotCakeSmoothie","thu"],R:["mixedBeanChilli","thu"],D:["mushroomGingerCashewStirFry","thu"],snacks:"Trail mix · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"chickpeaSaladBowl",D:"chilliTofu",snacks:"Rice cakes + almond butter · Veg batons + hummus"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"cauliflowerSteaksTahini",D:"spicyBeanNachos",snacks:"Mixed nuts · Fresh fruit"},
]},
{cycle:2,week:2,days:[
  {day:"mon",B:"gogoGreenSmoothie",R:"mixedBeanChilli",D:"creamyTomatoPasta",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["gogoGreenSmoothie","mon"],R:["mixedBeanChilli","mon"],D:["creamyTomatoPasta","mon"],snacks:"Banana · Veg batons + hummus"},
  {day:"wed",B:"carrotCakeSmoothie",L:"cauliflowerSteaksTahini",D:"thaiCarrotSoup",snacks:"Trail mix · Fresh fruit"},
  {day:"thu",B:"spicedBerryPorridge",R:"gfTomatoBeanPasta",D:"chilliTofu",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["spicedBerryPorridge","thu"],R:["gfTomatoBeanPasta","thu"],D:["chilliTofu","thu"],snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"spicyBeanNachos",D:"mushroomGingerCashewStirFry",snacks:"Trail mix · Fresh fruit"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"splitPeaSpinachSoup",D:"chickpeaSaladBowl",snacks:"Mixed nuts · Banana"},
]},
{cycle:2,week:3,days:[
  {day:"mon",B:"carrotCakeSmoothie",R:"gfTomatoBeanPasta",D:"chilliTofu",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["carrotCakeSmoothie","mon"],R:["gfTomatoBeanPasta","mon"],D:["chilliTofu","mon"],snacks:"Banana · Trail mix"},
  {day:"wed",B:"spicedBerryPorridge",L:"chickpeaSaladBowl",D:"mushroomGingerCashewStirFry",snacks:"Trail mix · Orange"},
  {day:"thu",B:"gogoGreenSmoothie",R:"roastedVegQuinoa",D:"thaiCarrotSoup",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["gogoGreenSmoothie","thu"],R:["roastedVegQuinoa","thu"],D:["thaiCarrotSoup","thu"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"cauliflowerSteaksTahini",D:"creamyTomatoPasta",snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"splitPeaSpinachSoup",D:"spicyBeanNachos",snacks:"Trail mix · Banana"},
]},
{cycle:2,week:4,days:[
  {day:"mon",B:"spicedBerryPorridge",R:"mixedBeanChilli",D:"mushroomGingerCashewStirFry",snacks:"Mixed nuts · Fresh fruit"},
  {day:"tue",B:["spicedBerryPorridge","mon"],R:["mixedBeanChilli","mon"],D:["mushroomGingerCashewStirFry","mon"],snacks:"Banana · Veg batons + hummus"},
  {day:"wed",B:"gogoGreenSmoothie",L:"spicyBeanNachos",D:"chilliTofu",snacks:"Trail mix · Orange"},
  {day:"thu",B:"carrotCakeSmoothie",R:"roastedVegQuinoa",D:"creamyTomatoPasta",snacks:"Mixed nuts · Banana"},
  {day:"fri",B:["carrotCakeSmoothie","thu"],R:["roastedVegQuinoa","thu"],D:["creamyTomatoPasta","thu"],snacks:"Rice cakes + almond butter · Fresh fruit"},
  {day:"sat",B:"coconutChiaPudding",L:"splitPeaSpinachSoup",D:"thaiCarrotSoup",snacks:"Trail mix · Fresh fruit"},
  {day:"sun",B:["coconutChiaPudding","sat"],L:"chickpeaSaladBowl",D:"cauliflowerSteaksTahini",snacks:"Mixed nuts · Banana"},
]},
{cycle:3,week:1,days:[
  {day:"mon",B:"chocolateProteinPorridge",R:"paella",D:"chickpeaAubergineCurry",snacks:"Mixed nuts · Banana nicecream"},
  {day:"tue",B:["chocolateProteinPorridge","mon"],R:["paella","mon"],D:["chickpeaAubergineCurry","mon"],snacks:"Banana nicecream · Trail mix"},
  {day:"wed",B:"avocadoBerrySmoothie",L:"roastedSquashQuinoaSalad",D:"coconutDaal",snacks:"Trail mix · Orange"},
  {day:"thu",B:["avocadoBerrySmoothie","wed"],R:"beanTacos",D:["coconutDaal","wed"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"fri",B:"bananaDatCinnamonSmoothie",R:"chickpeaPancakes",D:"chargrillTofuMisoAubergine",snacks:"Trail mix · Fresh fruit"},
  {day:"sat",B:["bananaDatCinnamonSmoothie","fri"],L:"butternutSquashCoconutSoup",D:["chargrillTofuMisoAubergine","fri"],snacks:"Rice cakes + almond butter · Banana"},
  {day:"sun",B:"avocadoBerrySmoothie",L:"spicyNoodleSalad",D:"chilliSinCarne",snacks:"Mixed nuts · Fresh fruit"},
]},
{cycle:3,week:2,days:[
  {day:"mon",B:"avocadoBerrySmoothie",R:"gfMinestrone",D:"coconutDaal",snacks:"Mixed nuts · Banana nicecream"},
  {day:"tue",B:["avocadoBerrySmoothie","mon"],R:["gfMinestrone","mon"],D:["coconutDaal","mon"],snacks:"Trail mix · Fresh fruit"},
  {day:"wed",B:"bananaDatCinnamonSmoothie",L:"spicyNoodleSalad",D:"chargrillTofuMisoAubergine",snacks:"Trail mix · Orange"},
  {day:"thu",B:["bananaDatCinnamonSmoothie","wed"],R:"chickpeaPancakes",D:["chargrillTofuMisoAubergine","wed"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"fri",B:"chocolateProteinPorridge",R:"beanTacos",D:"spicyPeanutNoodles",snacks:"Mixed nuts · Fresh fruit"},
  {day:"sat",B:["chocolateProteinPorridge","fri"],L:"roastedSquashQuinoaSalad",D:["spicyPeanutNoodles","fri"],snacks:"Rice cakes + almond butter · Banana"},
  {day:"sun",B:"avocadoBerrySmoothie",L:"butternutSquashCoconutSoup",D:"chickpeaAubergineCurry",snacks:"Mixed nuts · Fresh fruit"},
]},
{cycle:3,week:3,days:[
  {day:"mon",B:"bananaDatCinnamonSmoothie",R:"beanTacos",D:"chargrillTofuMisoAubergine",snacks:"Mixed nuts · Banana nicecream"},
  {day:"tue",B:["bananaDatCinnamonSmoothie","mon"],R:["beanTacos","mon"],D:["chargrillTofuMisoAubergine","mon"],snacks:"Trail mix · Fresh fruit"},
  {day:"wed",B:"chocolateProteinPorridge",L:"butternutSquashCoconutSoup",D:"chilliSinCarne",snacks:"Trail mix · Orange"},
  {day:"thu",B:["chocolateProteinPorridge","wed"],R:"gfMinestrone",D:["chilliSinCarne","wed"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"fri",B:"avocadoBerrySmoothie",R:"paella",D:"spicyPeanutNoodles",snacks:"Mixed nuts · Fresh fruit"},
  {day:"sat",B:["avocadoBerrySmoothie","fri"],L:"proteinPowerBowl",D:["spicyPeanutNoodles","fri"],snacks:"Rice cakes + almond butter · Banana"},
  {day:"sun",B:"bananaDatCinnamonSmoothie",L:"roastedSquashQuinoaSalad",D:"chickpeaAubergineCurry",snacks:"Mixed nuts · Fresh fruit"},
]},
{cycle:3,week:4,days:[
  {day:"mon",B:"chocolateProteinPorridge",R:"chickpeaPancakes",D:"chilliSinCarne",snacks:"Mixed nuts · Banana nicecream"},
  {day:"tue",B:["chocolateProteinPorridge","mon"],R:["chickpeaPancakes","mon"],D:["chilliSinCarne","mon"],snacks:"Trail mix · Fresh fruit"},
  {day:"wed",B:"avocadoBerrySmoothie",L:"spicyNoodleSalad",D:"spicyPeanutNoodles",snacks:"Trail mix · Orange"},
  {day:"thu",B:["avocadoBerrySmoothie","wed"],R:"paella",D:["spicyPeanutNoodles","wed"],snacks:"Veg batons + hummus · Fresh fruit"},
  {day:"fri",B:"bananaDatCinnamonSmoothie",R:"beanTacos",D:"coconutDaal",snacks:"Mixed nuts · Fresh fruit"},
  {day:"sat",B:["bananaDatCinnamonSmoothie","fri"],L:"proteinPowerBowl",D:["coconutDaal","fri"],snacks:"Rice cakes + almond butter · Banana"},
  {day:"sun",B:"chocolateProteinPorridge",L:"butternutSquashCoconutSoup",D:"chargrillTofuMisoAubergine",snacks:"Mixed nuts · Fresh fruit"},
]},
]
