// Cycle 1 adapted recipes (18)
[
{id:"huevosRancheros",name:"Plant-based Huevos Rancheros",cycle:1,mealTypes:["refuel"],prep:10,cook:15,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"1",n:"red pepper, finely diced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"260g",n:"tinned chopped tomatoes"},
  {q:"1 tsp",n:"smoked paprika"},
  {q:"280g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"4 small",n:"GF corn tortillas",gf:true},
  {q:"200g",n:"tinned black beans, drained"},
  {q:"40g",n:"Violife feta-style, crumbled",gf:true},
  {q:"small bunch",n:"coriander, roughly chopped"},
],
method:[
  "Heat 1 tsp oil in a pan; fry onion, pepper and garlic 5 mins until soft. Add tomatoes and paprika; simmer 5 mins until thickened.",
  "Heat remaining oil in a second pan. Add crumbled tofu, turmeric, nutritional yeast and tamari; stir-fry 3–4 mins until golden and fragrant.",
  "Warm tortillas under the grill. Heat beans in the microwave 2 mins.",
  "Spoon tomato sauce over tortillas, top with beans and tofu scramble. Finish with vegan feta and coriander.",
],
free:false,adaptations:[
  {orig:"Fried eggs",swap:"Scrambled tofu (turmeric + nutritional yeast + tamari)"},
  {orig:"Feta",swap:"Violife feta-style"},
],
gfCheck:["Corn tortillas — Old El Paso GF ✓ or Mission GF ✓","Violife feta-style — GF ✓ (check label)","Tamari — Kikkoman GF ✓"],
tags:["quick"],note:"Batch-cook the tomato sauce and freeze for up to 1 month. Makes 2 portions."},

{id:"quinoaProteinPancakes",name:"Quinoa Protein Pancakes with Spiced Berries",cycle:1,mealTypes:["refuel"],prep:10,cook:10,
ingredients:[
  {q:"4 tbsp",n:"ground flaxseed"},
  {q:"12 tbsp",n:"water (for flax eggs)"},
  {q:"290g",n:"cooked quinoa (100g uncooked weight)"},
  {q:"50g",n:"GF vanilla protein powder",gf:true},
  {q:"2 tsp",n:"honey or maple syrup"},
  {q:"1 tsp",n:"ground cinnamon"},
  {q:"4 tsp",n:"coconut oil"},
  {q:"150g",n:"mixed berries"},
  {q:"1 tsp",n:"mixed spice"},
],
method:[
  "Mix ground flaxseed with water; leave 5–10 mins to form flax eggs.",
  "Blend flax eggs, quinoa, protein powder, honey and cinnamon in a liquidiser until smooth.",
  "Melt coconut oil in a frying pan over medium-high heat; fry large spoonfuls of batter 1 min per side until golden. Repeat with remaining batter.",
  "Roughly mash berries with a fork, stir through mixed spice. Stack pancakes and spoon berries over to serve.",
],
free:false,adaptations:[
  {orig:"1 egg + 2 egg whites",swap:"4 tbsp ground flaxseed + 12 tbsp water (flax eggs)"},
  {orig:"Vanilla protein powder",swap:"GF vanilla protein powder (Pulsin or Nuzest)"},
],
gfCheck:["Protein powder — Pulsin or Nuzest GF ✓"],
tags:["quick","family"],note:"Cook quinoa the night before to save time. Makes 2 portions."},

{id:"cornbreadSpicyTofu",name:"Cornbread with Spicy Tofu Scramble & Avocado",cycle:1,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"100g",n:"medium or coarse cornmeal"},
  {q:"2 tbsp",n:"ground flaxseed"},
  {q:"6 tbsp",n:"water (for flax egg)"},
  {q:"120g",n:"soya yoghurt"},
  {q:"1 tsp",n:"GF baking powder",gf:true},
  {q:"2 tsp",n:"brown sugar"},
  {q:"large pinch",n:"smoked paprika"},
  {q:"salt and pepper",n:"to season"},
  {q:"300g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"1 tsp",n:"olive oil"},
  {q:"2 tsp",n:"chilli sauce"},
  {q:"70g",n:"avocado, sliced"},
],
method:[
  "Mix flaxseed with water; leave 5 mins. Preheat oven to 220°C.",
  "Whisk cornmeal, flax egg, 100g yoghurt, baking powder, sugar, paprika and seasoning to a batter. Pour into a hot, small ovenproof frying pan; fry 1 min then bake 6–8 mins until risen and golden.",
  "Heat oil in a pan; fry tofu with turmeric, nutritional yeast and tamari 3–4 mins until golden scrambled.",
  "Slide cornbread onto plates. Top with tofu scramble and remaining yoghurt; drizzle with chilli sauce and serve with avocado.",
],
free:false,adaptations:[
  {orig:"3 eggs (1 in batter, 2 fried on top)",swap:"Flax egg in batter; scrambled tofu on top"},
  {orig:"Greek/natural yoghurt",swap:"Soya yoghurt"},
],
gfCheck:["Baking powder — Dr. Oetker GF ✓","Tamari — Kikkoman GF ✓"],
tags:["quick"],note:"Cornmeal is naturally GF — double-check your brand. Makes 2 portions."},

{id:"bananaCoconutMuffins",name:"Banana & Coconut Protein Muffins",cycle:1,mealTypes:["refuel"],prep:15,cook:15,
ingredients:[
  {q:"195g",n:"GF self-raising flour",gf:true},
  {q:"45g",n:"desiccated coconut"},
  {q:"2 tsp",n:"ground cinnamon"},
  {q:"1½ tsp",n:"bicarbonate of soda"},
  {q:"pinch",n:"salt"},
  {q:"100g",n:"GF vanilla protein powder",gf:true},
  {q:"3 tbsp",n:"ground flaxseed"},
  {q:"9 tbsp",n:"water (for flax eggs)"},
  {q:"25g",n:"coconut oil, melted"},
  {q:"265ml",n:"coconut yoghurt"},
  {q:"90g",n:"honey"},
  {q:"95ml",n:"GF oat milk or full-fat coconut milk",gf:true},
  {q:"390g",n:"ripe banana, mashed (approx 4 medium)"},
],
method:[
  "Preheat oven to 180°C. Line a 12-hole muffin tin with paper cases. Mix flaxseed with water; rest 5 mins.",
  "Combine flour, coconut, cinnamon, bicarbonate of soda and salt in a large bowl; make a well.",
  "Blend flax eggs, coconut oil, coconut yoghurt, honey and oat milk until smooth; pour into dry ingredients and fold together.",
  "Fold in mashed banana; divide between cases and bake 15 mins until risen and golden. Cool before eating.",
],
free:false,adaptations:[
  {orig:"Plain wheat flour",swap:"GF self-raising flour (Doves Farm)"},
  {orig:"3 large eggs",swap:"3 flax eggs (3 tbsp ground flaxseed + 9 tbsp water)"},
  {orig:"Reduced-fat soured cream",swap:"Coconut yoghurt"},
  {orig:"Skimmed milk",swap:"GF oat milk or full-fat coconut milk"},
],
gfCheck:["GF self-raising flour — Doves Farm ✓","Protein powder — Pulsin or Nuzest GF ✓","Oat milk — GF certified (if using)"],
tags:["batch","otg"],note:"Makes 12 muffins — 6 servings of 2. Freeze individually wrapped without paper cases."},

{id:"mushroomBurger",name:"Mushroom & Lentil Burger",cycle:1,mealTypes:["refuel"],prep:15,cook:20,
ingredients:[
  {q:"8 tsp",n:"olive oil"},
  {q:"80g",n:"spring onions, finely chopped"},
  {q:"200g",n:"mushrooms, roughly chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"120g",n:"cooked green lentils, drained and patted dry"},
  {q:"60g",n:"gram flour (chickpea flour)"},
  {q:"small bunch",n:"parsley, chopped"},
  {q:"4 tbsp",n:"aquafaba (chickpea brine) or 2 flax eggs"},
  {q:"40g",n:"GF breadcrumbs",gf:true},
  {q:"salt and pepper",n:"to season"},
  {q:"60g",n:"vegan mayo",gf:true},
  {q:"1 tbsp",n:"grain mustard or Dijon mustard"},
  {q:"2",n:"GF burger buns, split and toasted",gf:true},
  {q:"handful",n:"lettuce leaves"},
],
method:[
  "Preheat oven to 180°C. Heat half the oil; fry spring onions, mushrooms and garlic 5 mins until soft.",
  "Blend mushroom mixture with lentils, gram flour, parsley, aquafaba and breadcrumbs to a coarse paste. Shape into 2 thick patties; chill 30 mins if soft.",
  "Heat remaining oil; fry patties 2 mins each side until golden. Slide into oven 5 mins to heat through.",
  "Stir mustard into mayo; spread on buns. Build burgers with lettuce and serve.",
],
free:false,adaptations:[
  {orig:"Egg white",swap:"Aquafaba (chickpea brine) or flax egg"},
  {orig:"Wholemeal breadcrumbs",swap:"GF breadcrumbs (Orgran or Doves Farm)"},
  {orig:"Burger bun",swap:"GF burger bun (Warburtons GF or Genius)"},
  {orig:"Mayonnaise",swap:"Vegan mayo (Hellmann's Vegan or similar)"},
],
gfCheck:["GF breadcrumbs — Orgran ✓ or Doves Farm ✓","GF burger buns — Warburtons GF ✓ or Genius GF ✓","Vegan mayo — Hellmann's Vegan ✓ (check label)"],
tags:["family"],note:"Pat lentils very dry before blending — wet lentils make patties hard to shape. Makes 2 portions."},

{id:"sweetPotatoSamosas",name:"Sweet Potato Samosas",cycle:1,mealTypes:["refuel"],prep:20,cook:35,
ingredients:[
  {q:"150g",n:"GF plain flour, plus extra for dusting",gf:true},
  {q:"75g",n:"coconut oil or cold vegan butter"},
  {q:"4–5 tbsp",n:"cold water"},
  {q:"200g",n:"sweet potato, diced"},
  {q:"2 tsp",n:"coconut oil"},
  {q:"2 small",n:"onions, finely chopped"},
  {q:"20g",n:"fresh ginger, grated"},
  {q:"2 tsp",n:"mustard seeds"},
  {q:"2 tsp",n:"garam masala"},
  {q:"1 tsp",n:"ground cumin"},
  {q:"1 tsp",n:"smoked paprika or chilli powder"},
  {q:"120g",n:"frozen peas"},
  {q:"20g",n:"GF unflavoured protein powder",gf:true},
  {q:"small bunch",n:"coriander, chopped"},
  {q:"salt and pepper",n:"to season"},
],
method:[
  "Make GF pastry: rub coconut oil into flour until like breadcrumbs; add cold water 1 tbsp at a time to form a firm dough. Wrap and chill 10 mins.",
  "Preheat oven to 200°C. Boil sweet potato 5–10 mins until soft; drain and roughly mash.",
  "Fry onion and ginger in coconut oil 5 mins. Add spices and peas; fry 2 mins. Stir in protein powder and a splash of water; crush peas roughly. Mix with sweet potato and coriander; season.",
  "Roll pastry thin on a floured surface; cut into 6 squares. Place a spoonful of filling in each, fold into triangles and press edges to seal. Brush with melted coconut oil; bake 25 mins until golden.",
],
free:false,adaptations:[
  {orig:"Filo pastry",swap:"GF shortcrust (GF plain flour + coconut oil + cold water)"},
  {orig:"Melted butter",swap:"Melted coconut oil for brushing"},
],
gfCheck:["GF plain flour — Doves Farm ✓","Protein powder — Pulsin GF ✓ (unflavoured)"],
tags:["batch","otg"],note:"Makes approx 6 samosas. Freeze before baking; cook from frozen at 200°C for 30–35 mins."},

{id:"spinachMushroomPizza",name:"Spinach & Mushroom Pizza",cycle:1,mealTypes:["refuel"],prep:15,cook:15,
ingredients:[
  {q:"70g",n:"GF self-raising flour",gf:true},
  {q:"70g",n:"gram flour (chickpea flour)"},
  {q:"½ tsp",n:"GF baking powder",gf:true},
  {q:"pinch",n:"salt"},
  {q:"130g",n:"coconut yoghurt"},
  {q:"100ml",n:"passata"},
  {q:"pinch",n:"dried mixed herbs"},
  {q:"large handful",n:"baby spinach"},
  {q:"90g",n:"Violife mozzarella-style, grated",gf:true},
  {q:"200g",n:"mushrooms, sliced"},
],
method:[
  "Preheat oven to 220°C. Wilt spinach in a splash of water; drain thoroughly and squeeze out all moisture. Roughly chop.",
  "Combine flours, baking powder and salt; add coconut yoghurt and stir to a dough. Knead briefly then roll into two thin rounds.",
  "Dry-fry each base 2 mins per side in a hot pan until golden. Transfer to a baking tray; spread with passata and herbs.",
  "Top with spinach, Violife mozzarella and mushrooms; bake 8–10 mins until cheese is golden and bubbling.",
],
free:false,adaptations:[
  {orig:"Self-raising wheat flour",swap:"GF self-raising flour (Doves Farm)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
  {orig:"Dairy mozzarella",swap:"Violife mozzarella-style"},
],
gfCheck:["GF self-raising flour — Doves Farm ✓","GF baking powder — Dr. Oetker GF ✓","Violife mozzarella — GF ✓ (check label)"],
tags:["batch","family"],note:"Pizza bases can be made ahead and frozen. Makes 2 portions."},

{id:"falafelRoastPepperBagel",name:"Falafel & Roast Pepper Bagel",cycle:1,mealTypes:["refuel"],prep:15,cook:25,
ingredients:[
  {q:"1",n:"red pepper, deseeded and halved"},
  {q:"2 tsp",n:"olive oil"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"1 clove",n:"garlic, crushed"},
  {q:"2 tsp",n:"ground cumin"},
  {q:"1 tsp",n:"turmeric"},
  {q:"pinch",n:"smoked paprika"},
  {q:"290g",n:"tinned chickpeas, drained — reserve brine"},
  {q:"3 tbsp",n:"aquafaba (brine from tin)"},
  {q:"small bunch",n:"parsley"},
  {q:"salt and pepper",n:"to season"},
  {q:"2",n:"GF bagels, split and toasted",gf:true},
  {q:"60g",n:"coconut yoghurt"},
  {q:"handful",n:"rocket"},
],
method:[
  "Preheat oven to 180°C; line a baking tray. Roast pepper halves 15–20 mins until soft.",
  "Heat oil; fry onion and garlic 5 mins. Add spices and chickpeas; fry 2 mins. Blend with aquafaba, parsley and seasoning to a coarse paste.",
  "With wet hands, roll into bite-sized balls; place on tray beside peppers and bake 12–15 mins until crisp outside.",
  "Spread GF bagels with coconut yoghurt; layer rocket, falafel and roasted peppers.",
],
free:false,adaptations:[
  {orig:"Egg white",swap:"Aquafaba (reserved brine from chickpea tin — zero waste)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
  {orig:"Plain wheat bagel",swap:"GF bagel (Warburtons GF or Genius)"},
],
gfCheck:["GF bagels — Warburtons GF ✓ or Genius GF ✓"],
tags:["otg"],note:"Jarred roasted peppers in brine (not oil) save time. Makes 2 portions."},

{id:"sweetPotatoGnocchi",name:"Sweet Potato Gnocchi with Creamy Spinach",cycle:1,mealTypes:["refuel"],prep:15,cook:20,
ingredients:[
  {q:"2 medium",n:"sweet potatoes (approx 180g flesh total)"},
  {q:"150g",n:"gram flour (chickpea flour), plus extra for dusting"},
  {q:"pinch",n:"salt"},
  {q:"400g",n:"baby leaf spinach"},
  {q:"pinch",n:"nutmeg"},
  {q:"60g",n:"Violife cream cheese-style",gf:true},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Microwave sweet potatoes 8–10 mins until soft; scoop flesh into a bowl. Mix in gram flour and salt to a soft dough.",
  "Roll dough into a sausage 1cm thick; cut into 2.5cm lengths. Boil in salted water 2 mins; drain.",
  "Wilt spinach in a splash of water; squeeze out moisture. Blend with nutmeg, Violife cream cheese and half the nutritional yeast until smooth.",
  "Warm sauce in pan; stir in gnocchi. Divide into bowls; scatter over remaining nutritional yeast.",
],
free:false,adaptations:[
  {orig:"Low-fat cream cheese",swap:"Violife cream cheese-style"},
  {orig:"Hard cheese (grated)",swap:"Nutritional yeast"},
],
gfCheck:["Violife cream cheese — GF ✓ (check current label)"],
tags:["batch"],note:"Gnocchi can be boiled ahead and chilled in cold water up to 2 days. Makes 2 portions."},

{id:"spinachFetaFrittata",name:"Loaded Spinach & Vegan Feta Frittata",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"8",n:"spring onions, sliced"},
  {q:"400g",n:"baby leaf spinach"},
  {q:"130g",n:"cooked new potatoes, sliced"},
  {q:"pinch",n:"freshly grated nutmeg"},
  {q:"salt and pepper",n:"to season"},
  {q:"120g",n:"gram flour (chickpea flour)"},
  {q:"240ml",n:"water"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"½ tsp",n:"turmeric"},
  {q:"90g",n:"Violife feta-style, crumbled",gf:true},
  {q:"green salad",n:"to serve"},
],
method:[
  "Preheat grill to highest setting. Whisk gram flour, water, nutritional yeast and turmeric to a smooth batter.",
  "Heat oil in a medium non-stick ovenproof frying pan. Fry spring onions 2 mins; add spinach in batches until wilted. Squeeze out moisture on kitchen paper.",
  "Return spinach and spring onions to pan; arrange potatoes on top and season with nutmeg, salt and pepper. Pour chickpea batter over; shake pan gently.",
  "Cook over medium heat until batter is almost set. Crumble Violife feta over the top; slide under grill 3 mins until golden. Cut into wedges.",
],
free:false,adaptations:[
  {orig:"8 eggs + 4 egg whites",swap:"Chickpea flour batter (gram flour + water + nutritional yeast + turmeric)"},
  {orig:"Feta",swap:"Violife feta-style"},
],
gfCheck:["Violife feta-style — GF ✓ (check current label)"],
tags:["batch"],note:"Original serves 3; scaled to 2 here. Keeps in fridge up to 3 days. Makes 2 portions."},

{id:"bakedGreenEggsWithPesto",name:"Baked Greens with Tofu & Spinach Pesto",cycle:1,mealTypes:["breakfast","lunch"],prep:10,cook:15,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"200g",n:"leeks, chopped"},
  {q:"350g",n:"baby leaf spinach"},
  {q:"100g",n:"coconut yoghurt"},
  {q:"salt and pepper",n:"to season"},
  {q:"300g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"50g",n:"baby leaf spinach (for pesto)"},
  {q:"small bunch",n:"basil"},
  {q:"40g",n:"unsalted roasted cashews"},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Preheat oven to 180°C. Fry leeks in oil 5 mins; add 350g spinach and wilt 1 min. Remove from heat; stir in coconut yoghurt, season.",
  "Season tofu with turmeric and tamari. Spoon leek mixture into an ovenproof dish; press seasoned tofu into wells in the mixture. Bake 12–15 mins until set.",
  "Blend remaining spinach, basil, cashews and nutritional yeast with a pinch of salt until a rough pesto forms.",
  "Spoon pesto over the dish and serve.",
],
free:false,adaptations:[
  {orig:"2 baked eggs",swap:"Seasoned firm tofu (turmeric + tamari) baked in the wells"},
  {orig:"Hard cheese in pesto",swap:"Nutritional yeast"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:["Tamari — Kikkoman GF ✓"],
tags:["quick"],note:"Pesto keeps 3 days in the fridge. Makes 2 portions."},

{id:"tofuShakshuka",name:"Tofu Shakshuka",cycle:1,mealTypes:["breakfast","lunch"],prep:10,cook:15,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"1",n:"red onion, finely sliced"},
  {q:"2",n:"red peppers, sliced"},
  {q:"1 tsp",n:"smoked paprika, plus extra to serve"},
  {q:"1 tsp",n:"ground cumin"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"270g",n:"tinned chopped tomatoes"},
  {q:"200g",n:"tinned chickpeas, drained"},
  {q:"salt and pepper",n:"to season"},
  {q:"400g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"100g",n:"coconut yoghurt"},
  {q:"30g",n:"tahini"},
],
method:[
  "Heat oil; fry onion and pepper 5 mins. Add spices and tomato purée; fry 1 min. Pour in tomatoes and chickpeas; simmer 8–10 mins until thickened.",
  "Mix crumbled tofu with turmeric, nutritional yeast and tamari. Press into wells in the sauce; cover and cook gently 4–5 mins.",
  "Mix coconut yoghurt with tahini. Spoon over the top; finish with a pinch of smoked paprika.",
],
free:false,adaptations:[
  {orig:"Poached eggs",swap:"Seasoned scrambled tofu (turmeric + nutritional yeast + tamari)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:["Tamari — Kikkoman GF ✓"],
tags:["batch","family"],note:"Make the sauce in bulk and freeze; add tofu fresh when reheating. Makes 2 portions."},

{id:"sweetcornFritters",name:"Sweetcorn Fritters with Avocado & Chilli",cycle:1,mealTypes:["breakfast","lunch"],prep:10,cook:10,
ingredients:[
  {q:"80g",n:"gram flour (chickpea flour)"},
  {q:"60ml",n:"water"},
  {q:"large pinch",n:"smoked paprika or chilli powder"},
  {q:"270g",n:"tinned sweetcorn, drained"},
  {q:"120g",n:"edamame beans (soya beans)"},
  {q:"80g",n:"spring onions, finely chopped"},
  {q:"salt and pepper",n:"to season"},
  {q:"2 tsp",n:"olive oil"},
  {q:"70g",n:"avocado, sliced"},
  {q:"80g",n:"coconut yoghurt"},
  {q:"small bunch",n:"coriander, chopped"},
],
method:[
  "Blend gram flour, water, paprika, sweetcorn, edamame and spring onions in a food processor; pulse to a rough paste, leaving some texture.",
  "Heat oil in a frying pan over medium-high heat; drop large spoonfuls of mixture into pan. Fry 2 mins each side until golden.",
  "Serve fritters with avocado, coconut yoghurt, coriander and an extra pinch of paprika.",
],
free:false,adaptations:[
  {orig:"Plain wheat flour + egg + egg white",swap:"Gram flour + water (chickpea flour binds naturally — no egg needed)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:[],tags:["quick","otg"],note:"Gram flour batter is naturally GF. Edamame beans are in the freezer aisle. Makes 2 portions."},

{id:"cauliflowerCheeseSoup",name:"Cauliflower 'Cheese' Soup",cycle:1,mealTypes:["lunch","dinner"],prep:5,cook:20,
ingredients:[
  {q:"1 tbsp",n:"coconut oil or vegan butter"},
  {q:"400g",n:"cauliflower florets, sliced"},
  {q:"pinch",n:"nutmeg"},
  {q:"200g",n:"tinned chickpeas, drained"},
  {q:"40g",n:"GF unflavoured protein powder",gf:true},
  {q:"530ml",n:"full-fat tinned coconut milk"},
  {q:"salt and pepper",n:"to season"},
  {q:"8 tbsp",n:"nutritional yeast"},
],
method:[
  "Melt coconut oil in a saucepan; fry cauliflower and nutmeg 3–4 mins until starting to soften.",
  "Add chickpeas, protein powder and coconut milk; bring to a simmer. Cover and cook 8–10 mins.",
  "Stir in most of the nutritional yeast and seasoning. Blend until smooth.",
  "Ladle into bowls and scatter over remaining nutritional yeast.",
],
free:false,adaptations:[
  {orig:"Butter",swap:"Coconut oil or vegan butter"},
  {orig:"Skimmed milk",swap:"Full-fat coconut milk"},
  {orig:"Mature cheddar",swap:"Nutritional yeast"},
],
gfCheck:["Protein powder — Pulsin unflavoured GF ✓"],
tags:["batch","otg"],note:"Freezes well. Reheat with an extra splash of coconut milk. Makes 2 portions."},

{id:"grilledHalloumiLentilSalad",name:"Grilled Vegan Halloumi, Pepper & Lentil Salad",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:10,
ingredients:[
  {q:"1",n:"red pepper, deseeded and quartered"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"160g",n:"Violife halloumi-style, sliced",gf:true},
  {q:"140g",n:"cooked lentils"},
  {q:"120g",n:"cherry tomatoes, halved"},
  {q:"juice of 1",n:"lemon"},
  {q:"small bunch",n:"parsley, chopped"},
  {q:"pinch",n:"chilli flakes"},
  {q:"pinch",n:"dried oregano"},
  {q:"2 handfuls",n:"rocket or watercress"},
],
method:[
  "Preheat a griddle pan over high heat. Brush peppers with a little oil; griddle 4–5 mins each side until charred. Roughly chop.",
  "Brush Violife halloumi with remaining oil; griddle 1–2 mins each side until golden and marked.",
  "Toss peppers with lentils, tomatoes, lemon juice, parsley, chilli flakes, oregano and rocket. Serve salad topped with grilled halloumi.",
],
free:false,adaptations:[{orig:"Dairy halloumi",swap:"Violife halloumi-style (or extra-firm tofu, pressed and grilled)"}],
gfCheck:["Violife halloumi-style — GF ✓ (check current label)"],
tags:["quick","otg"],note:"Ready-cooked lentils speed this up. Makes 2 portions."},

{id:"courgetteCannelloni",name:"Courgette Cannelloni",cycle:1,mealTypes:["lunch","dinner"],prep:15,cook:30,
ingredients:[
  {q:"4 medium",n:"courgettes"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"280g",n:"tinned chopped tomatoes"},
  {q:"120g",n:"raw unsalted cashews, soaked 30 mins and drained"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"2 tbsp",n:"lemon juice"},
  {q:"salt and pepper",n:"to season"},
  {q:"40g",n:"Violife mozzarella-style, torn",gf:true},
],
method:[
  "Preheat oven to 200°C. Use an apple corer to hollow courgettes into tubes; finely chop the removed centres.",
  "Heat oil; fry chopped courgette centres with garlic 3–4 mins. Add tomato purée and tomatoes; simmer 2 mins. Season.",
  "Blend soaked cashews with nutritional yeast, lemon juice and seasoning to a thick cashew ricotta.",
  "Fill courgette tubes with cashew ricotta. Spoon half the sauce into a roasting dish; lay stuffed courgettes on top; pour over remaining sauce. Top with Violife mozzarella; bake 25 mins.",
],
free:false,adaptations:[
  {orig:"Ricotta",swap:"Cashew ricotta (soaked cashews + nutritional yeast + lemon juice)"},
  {orig:"Hard cheese",swap:"Nutritional yeast"},
  {orig:"Dairy mozzarella",swap:"Violife mozzarella-style"},
],
gfCheck:["Violife mozzarella — GF ✓ (check current label)"],
tags:["family","batch"],note:"Soak cashews in advance. Split courgettes lengthways if no apple corer. Makes 2 portions."},

{id:"broccoliQuiche",name:"Broccoli & Spring Onion Crustless Quiche",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:30,
ingredients:[
  {q:"200g",n:"broccoli florets"},
  {q:"120g",n:"frozen peas"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"8",n:"spring onions, sliced"},
  {q:"300g",n:"silken tofu"},
  {q:"120g",n:"gram flour (chickpea flour)"},
  {q:"240ml",n:"full-fat coconut milk"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"2 tbsp",n:"coconut yoghurt"},
  {q:"40g",n:"Violife cream cheese-style",gf:true},
  {q:"salt and pepper",n:"to season"},
  {q:"green salad",n:"to serve"},
],
method:[
  "Preheat oven to 180°C. Boil broccoli and peas 5 mins; drain. Fry spring onions in oil 2 mins until soft.",
  "Blend silken tofu, gram flour, coconut milk, nutritional yeast and coconut yoghurt until smooth; season.",
  "Arrange vegetables in an 18–20cm tart tin lined with greaseproof paper (or ovenproof frying pan). Pour over tofu batter; dot with Violife cream cheese.",
  "Bake 25–30 mins until set and lightly golden. Cool slightly before cutting into wedges.",
],
free:false,adaptations:[
  {orig:"3 eggs + 1 egg white",swap:"Silken tofu + gram flour + coconut milk batter"},
  {orig:"Low-fat crème fraîche",swap:"Coconut yoghurt"},
  {orig:"Soft goat's cheese",swap:"Violife cream cheese-style (or cashew cream)"},
],
gfCheck:["Violife cream cheese — GF ✓ (check current label)"],
tags:["batch"],note:"Keeps in fridge 2 days. Does not freeze well. Makes 2 portions."},

{id:"aubergineParmigiana",name:"Aubergine Parmigiana",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:35,
ingredients:[
  {q:"2 medium",n:"aubergines, sliced into 1cm rounds"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"300g",n:"tinned chopped tomatoes"},
  {q:"1 tbsp",n:"red wine vinegar"},
  {q:"pinch",n:"dried oregano"},
  {q:"salt and pepper",n:"to season"},
  {q:"150g",n:"Violife mozzarella-style, sliced",gf:true},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Preheat oven to 200°C. Brush aubergine with oil; fry in batches in a hot pan until golden on both sides.",
  "Add garlic to pan; fry 1 min. Add tomato purée, tomatoes, vinegar and oregano; simmer 2 mins. Season.",
  "Spoon half the sauce into a shallow roasting dish; arrange aubergine on top then spoon over remaining sauce. Lay Violife mozzarella over the top and scatter with nutritional yeast.",
  "Bake 25 mins until cheese is bubbling and golden.",
],
free:false,adaptations:[
  {orig:"Dairy mozzarella",swap:"Violife mozzarella-style"},
  {orig:"Hard cheese (grated)",swap:"Nutritional yeast"},
],
gfCheck:["Violife mozzarella — GF ✓ (check current label)"],
tags:["batch","family"],note:"Keeps well and reheats beautifully. Makes 2 portions."},
]
