// Cycle 1 core recipes (20)
[
{id:"coconutOvernightOats",name:"Coconut Overnight Oats",cycle:1,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"80g",n:"certified GF rolled oats",gf:true},
  {q:"400ml",n:"full-fat coconut milk"},
  {q:"2 tbsp",n:"chia seeds"},
  {q:"2 tsp",n:"maple syrup"},
  {q:"large handful",n:"mixed berries, fresh or frozen"},
],
method:[
  "Stir oats, coconut milk, chia seeds and maple syrup together.",
  "Divide into two jars. Refrigerate overnight or at least 4 hours.",
  "Top with berries. Eat cold or warm gently with a splash of coconut milk.",
],
free:false,adaptations:[{orig:"Regular oats",swap:"Certified GF rolled oats"}],
gfCheck:["Oats — must be certified GF (e.g. Nairn's GF Oats)"],
tags:["batch","otg"],note:"Prep the night before. Makes 2 portions."},

{id:"oatmealRaisinSmoothie",name:"Oatmeal Raisin Cookie Smoothie",cycle:1,mealTypes:["refuel"],prep:5,cook:0,
ingredients:[
  {q:"2 medium",n:"bananas"},
  {q:"280ml",n:"unsweetened almond milk"},
  {q:"140g",n:"soya yoghurt"},
  {q:"40g",n:"GF vanilla protein powder",gf:true},
  {q:"60g",n:"ground flaxseed"},
  {q:"40g",n:"certified GF rolled oats",gf:true},
  {q:"60g",n:"raisins"},
  {q:"large pinch",n:"ground cinnamon"},
  {q:"handful",n:"ice"},
],
method:[
  "Combine all ingredients in a liquidiser and blend until smooth.",
  "Adjust ice for desired thickness. Pour into two glasses.",
  "Tip: weigh dry ingredients into the blender the night before for a quicker morning.",
],
free:false,adaptations:[
  {orig:"Almond milk",swap:"Soya milk for nut-free"},
  {orig:"Greek yoghurt",swap:"Soya yoghurt"},
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin or Nuzest GF"],
tags:["quick"],note:"Post-workout refuel. Makes 2 portions."},

{id:"overnightOatsProtein",name:"Protein Overnight Oats",cycle:1,mealTypes:["refuel"],prep:10,cook:0,
ingredients:[
  {q:"50g",n:"GF vanilla protein powder",gf:true},
  {q:"150g",n:"soya yoghurt"},
  {q:"100g",n:"mixed berries"},
  {q:"150ml",n:"unsweetened almond milk"},
  {q:"2 tsp",n:"ground cinnamon"},
  {q:"80g",n:"certified GF rolled oats",gf:true},
  {q:"2 tsp",n:"honey or maple syrup"},
  {q:"30g",n:"flaked almonds"},
],
method:[
  "Blend protein powder, yoghurt, berries, almond milk and cinnamon until smooth.",
  "Pour into two bowls or jars and stir in the oats.",
  "Cover and refrigerate overnight or at least 4 hours.",
  "When ready, drizzle with honey and top with almonds. Loosen with a splash of milk if too thick.",
],
free:false,adaptations:[
  {orig:"Greek yoghurt",swap:"Soya yoghurt"},
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin or Nuzest"],
tags:["batch","otg"],note:"Prep the night before. Makes 2 portions."},

{id:"butternutSquashRisotto",name:"Butternut Squash Risotto",cycle:1,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"400g",n:"butternut squash, grated"},
  {q:"2",n:"GF vegetable stock cubes",gf:true},
  {q:"800ml",n:"boiling water"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"130g",n:"risotto rice"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"2 handfuls",n:"rocket or pea shoots"},
],
method:[
  "Microwave grated squash with 200ml stock for 5 mins until soft. Blend smooth.",
  "Fry onion in oil 5 mins. Add garlic 1 min. Stir in rice.",
  "Add remaining stock a ladle at a time over 18–20 mins, stirring continuously.",
  "Stir in squash purée and nutritional yeast. Season well. Top with rocket.",
],
free:false,adaptations:[{orig:"Hard cheese",swap:"Nutritional yeast"}],
gfCheck:["Stock cubes — Kallo GF or Marigold GF"],
tags:["batch"],note:"Eat within 1–2 hours after your workout. Makes 2 portions."},

{id:"pbJamSmoothie",name:"Peanut Butter & Jam Smoothie",cycle:1,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"260ml",n:"unsweetened almond milk"},
  {q:"130g",n:"fresh or frozen raspberries"},
  {q:"40g",n:"certified GF rolled oats",gf:true},
  {q:"160g",n:"soya yoghurt"},
  {q:"50g",n:"GF vanilla protein powder",gf:true},
  {q:"70g",n:"peanut butter"},
  {q:"handful",n:"ice"},
],
method:["Blend all ingredients until smooth. Pour into two glasses or jars."],
free:false,adaptations:[
  {orig:"Greek yoghurt",swap:"Soya yoghurt"},
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
],
gfCheck:["Oats — certified GF only","Protein powder — Pulsin or Nuzest GF"],
tags:["quick","otg"],note:"Quick, high-protein breakfast. Makes 2 portions."},

{id:"bananaCoconutSmoothie",name:"Banana & Coconut Smoothie",cycle:1,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"2",n:"ripe bananas"},
  {q:"400ml",n:"full-fat coconut milk"},
  {q:"2 tbsp",n:"almond butter"},
  {q:"½ tsp",n:"vanilla extract"},
  {q:"pinch",n:"cinnamon"},
  {q:"handful",n:"ice"},
],
method:["Blend everything until smooth. Pour into two glasses or jars."],
free:true,adaptations:[],gfCheck:[],
tags:["quick"],note:"Makes 2 portions — seal second in a jar and refrigerate."},

{id:"tuscanBeanStew",name:"Tuscan Bean & Kale Stew",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"2",n:"carrots, chopped"},
  {q:"2 sticks",n:"celery, chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"2",n:"GF vegetable stock cubes",gf:true},
  {q:"600ml",n:"boiling water"},
  {q:"390g",n:"tinned cannellini beans, drained"},
  {q:"large handful",n:"kale, shredded"},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Fry carrot and celery in oil 5 mins. Add garlic and tomato purée; cook 2 mins.",
  "Crumble in stock cubes, pour in water. Add beans and kale; simmer 10 mins.",
  "Stir in nutritional yeast. Season well.",
],
free:false,adaptations:[{orig:"Hard cheese",swap:"Nutritional yeast"}],
gfCheck:["Stock cubes — Kallo GF or Marigold GF"],
tags:["batch","otg"],note:""},

{id:"spicyTofuAsianSlaw",name:"Spicy Tofu with Asian Slaw",cycle:1,mealTypes:["lunch","dinner"],prep:15,cook:10,
ingredients:[
  {q:"1 tbsp",n:"sesame oil"},
  {q:"4 cloves",n:"garlic, crushed"},
  {q:"30g",n:"fresh ginger, grated"},
  {q:"1 tsp",n:"Sichuan peppercorns, crushed"},
  {q:"400g",n:"firm tofu, diced"},
  {q:"1 tsp",n:"cornflour"},
  {q:"30g",n:"peanut butter"},
  {q:"4 tsp",n:"sriracha sauce"},
  {q:"juice of 2",n:"limes"},
  {q:"400g",n:"red cabbage, shredded"},
  {q:"2",n:"carrots, shredded"},
  {q:"small bunch",n:"coriander"},
],
method:[
  "Heat oil in wok. Fry garlic, ginger, peppercorns 1 min. Add tofu 2 mins.",
  "Mix cornflour with a splash of water; pour over tofu and toss.",
  "Whisk peanut butter, sriracha, lime juice for dressing.",
  "Toss cabbage and carrot. Serve tofu on slaw with dressing and coriander.",
],
free:false,adaptations:[{orig:"Soy sauce",swap:"Tamari — certified GF"}],
gfCheck:[],tags:["quick","family"],note:""},

{id:"quinoaEdamameSalad",name:"Quinoa & Edamame Salad",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"160g",n:"quinoa"},
  {q:"2 tsp",n:"olive oil"},
  {q:"juice of 1",n:"lemon"},
  {q:"160g",n:"cherry tomatoes, halved"},
  {q:"2",n:"carrots, peeled into ribbons"},
  {q:"180g",n:"edamame beans (soya beans)"},
  {q:"200g",n:"kale, shredded"},
  {q:"40g",n:"pumpkin seeds"},
],
method:[
  "Cook quinoa in salted water 15 mins until fluffy. Drain.",
  "Dress warm quinoa with oil, lemon juice, salt and pepper.",
  "Add tomatoes, carrot ribbons, edamame, kale and pumpkin seeds. Toss and serve.",
],
free:true,adaptations:[
  {orig:"Pearl barley (not GF)",swap:"Quinoa"},
  {orig:"Soft goat's cheese",swap:"Extra pumpkin seeds"},
],
gfCheck:[],tags:["quick","otg"],note:"Quinoa keeps in the fridge for 3 days — great batch prep. Makes 2 portions."},

{id:"aaalooGobi",name:"Aloo Gobi",cycle:1,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"1 tbsp",n:"coconut oil"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"290g",n:"cauliflower florets"},
  {q:"410g",n:"potatoes, peeled and diced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"40g",n:"fresh ginger, grated"},
  {q:"1 tsp each",n:"turmeric, mustard seeds, ground cumin"},
  {q:"pinch",n:"chilli powder"},
  {q:"290g",n:"tinned chopped tomatoes"},
  {q:"120g",n:"coconut yoghurt"},
  {q:"small bunch",n:"coriander"},
  {q:"4",n:"rice poppadoms",gf:true},
],
method:[
  "Fry onion in coconut oil 5 mins. Add cauliflower and potato; fry 3–4 mins.",
  "Add garlic, ginger and spices; fry 1 min. Add tomatoes; simmer 15 mins.",
  "Remove from heat, stir in coconut yoghurt. Season. Top with coriander.",
  "Serve with rice poppadoms.",
],
free:false,adaptations:[
  {orig:"Greek yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
  {orig:"Regular poppadoms",swap:"Rice poppadoms — check GF label"},
],
gfCheck:["Rice poppadoms — check GF labelling"],
tags:["batch"],note:"Carb-rich refuel — potatoes provide good post-workout energy. Makes 2 portions."},

{id:"charredCornSalad",name:"Charred Corn Salad with Avocado",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"1",n:"corn on the cob (or 180g tinned sweetcorn)"},
  {q:"1 tsp",n:"olive oil"},
  {q:"pinch",n:"smoked paprika or chilli powder"},
  {q:"1",n:"ripe avocado, diced"},
  {q:"2 handfuls",n:"watercress or rocket"},
  {q:"juice of 2",n:"limes"},
  {q:"large bunch",n:"coriander, chopped"},
  {q:"30g",n:"sunflower seeds, toasted"},
  {q:"30g",n:"pumpkin seeds"},
],
method:[
  "Heat a griddle pan over high heat. Rub corn with oil, season with paprika.",
  "Grill 8–10 mins, turning, until charred. Slice kernels from cob into a bowl.",
  "Add avocado, watercress, lime juice, coriander and seeds. Toss and serve.",
],
free:true,adaptations:[{orig:"Feta",swap:"Sunflower seeds for texture and healthy fats"}],
gfCheck:[],tags:["quick","otg"],note:"Fresh and light. Tinned sweetcorn works when corn on the cob isn't in season. Makes 2 portions."},

{id:"sichuanAubergine",name:"Sichuan Spiced Aubergine",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"2 medium",n:"aubergines, cut into wedges"},
  {q:"1 tsp each",n:"coconut oil, sesame oil"},
  {q:"1 tsp",n:"Sichuan peppercorns, crushed"},
  {q:"4 cloves",n:"garlic, crushed"},
  {q:"20g",n:"fresh ginger, grated"},
  {q:"80g",n:"spring onions, chopped"},
  {q:"160g",n:"smoked tofu, diced"},
  {q:"4 tsp",n:"tamari (GF)",gf:true},
  {q:"4 tsp",n:"balsamic vinegar"},
  {q:"1 tsp",n:"cornflour"},
  {q:"60g",n:"roasted peanuts, crushed"},
],
method:[
  "Microwave aubergine wedges covered 5–6 mins until soft.",
  "Heat oils in wok. Fry peppercorns, garlic, ginger, spring onions 2 mins.",
  "Add tofu and aubergine. Mix tamari, vinegar and cornflour; pour over and toss.",
  "Serve scattered with crushed peanuts.",
],
free:false,adaptations:[{orig:"Dark soy sauce",swap:"Tamari — certified GF"}],
gfCheck:["Tamari — Kikkoman GF or Clearspring Tamari"],
tags:["quick","batch"],note:""},

{id:"almondPestoPasta",name:"Almond Pesto Pasta with Broccoli",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"140g",n:"edamame spaghetti or GF spaghetti"},
  {q:"140g",n:"tenderstem broccoli, sliced"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"large bunch",n:"fresh basil, leaves torn"},
  {q:"2 handfuls",n:"baby leaf spinach"},
  {q:"40g",n:"blanched almonds"},
  {q:"3 tbsp",n:"nutritional yeast"},
],
method:[
  "Bring a pan of salted water to the boil. Cook pasta per packet instructions; add broccoli 2 mins before end.",
  "Meanwhile blend oil, garlic, basil, spinach, almonds and nutritional yeast to a smooth pesto.",
  "Drain pasta and broccoli, toss with pesto and serve.",
],
free:false,adaptations:[{orig:"Hard cheese",swap:"Nutritional yeast"}],
gfCheck:[],tags:["quick","family"],note:"Edamame spaghetti is naturally GF and high-protein. Makes 2 portions."},

{id:"saagTofu",name:"Saag Tofu",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"320g",n:"baby leaf spinach"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"200g",n:"firm tofu, drained and diced"},
  {q:"1",n:"onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"30g",n:"fresh ginger, grated"},
  {q:"2",n:"green chillies, finely chopped"},
  {q:"1 tsp",n:"garam masala"},
  {q:"½ tsp",n:"turmeric"},
  {q:"4",n:"rice poppadoms",gf:true},
],
method:[
  "Heat a splash of water in a wok. Add spinach; stir until wilted. Drain thoroughly and roughly chop.",
  "Wipe wok; add coconut oil over high heat. Fry tofu 3–4 mins until golden. Remove and set aside.",
  "Fry onion, garlic, ginger and chilli until soft. Add spices; fry 1 min.",
  "Return tofu and spinach to pan. Toss together, season and serve with poppadoms.",
],
free:false,adaptations:[{orig:"Paneer",swap:"Firm tofu — drain and pat dry thoroughly before frying"}],
gfCheck:["Rice poppadoms — check GF labelling"],
tags:["family"],note:"Makes 2 portions. Serve with rice for a heartier meal."},

{id:"coconutChiaPudding",name:"Coconut Chia Pudding with Mango",cycle:1,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"6 tbsp",n:"chia seeds"},
  {q:"600ml",n:"full-fat coconut milk"},
  {q:"2 tsp",n:"maple syrup"},
  {q:"1",n:"ripe mango, diced"},
],
method:[
  "Stir chia seeds into coconut milk with maple syrup.",
  "Divide into two containers. Refrigerate overnight or at least 4 hours.",
  "Top with diced mango to serve.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","otg"],note:"Makes 2 portions. Stores in fridge up to 3 days."},

{id:"moroccanChickpeaStew",name:"Spicy Moroccan Chickpea Stew",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"red onion, diced"},
  {q:"1",n:"red pepper, diced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"4 tsp",n:"ras el hanout"},
  {q:"270g",n:"tinned chopped tomatoes"},
  {q:"330g",n:"tinned chickpeas, drained"},
  {q:"small bunch",n:"coriander"},
  {q:"80g",n:"coconut yoghurt"},
  {q:"40g",n:"toasted flaked almonds"},
],
method:[
  "Fry onion, pepper and garlic 5 mins. Add tomato purée and ras el hanout; fry 1 min.",
  "Add tomatoes; cook 5 mins. Add chickpeas; simmer 10 mins. Season.",
  "Top with coriander, coconut yoghurt and almonds.",
],
free:false,adaptations:[{orig:"Greek yoghurt",swap:"Coconut yoghurt"}],
gfCheck:[],tags:["batch","family"],note:""},

{id:"spicyMushroomLettuceCups",name:"Spicy Mushroom Lettuce Cups",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:10,
ingredients:[
  {q:"4 tsp",n:"tamari (GF)",gf:true},
  {q:"2 tsp",n:"sesame oil"},
  {q:"4 tsp",n:"sesame seeds"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"20g",n:"Thai red curry paste",gf:true},
  {q:"320g",n:"chestnut mushrooms, finely chopped"},
  {q:"200g",n:"frozen edamame beans, defrosted"},
  {q:"small bunch",n:"coriander"},
  {q:"2 heads",n:"baby gem lettuce, leaves separated"},
  {q:"40g",n:"peanut butter"},
  {q:"4 tsp",n:"sriracha"},
  {q:"juice of 2",n:"limes"},
],
method:[
  "Mix tamari, sesame oil and seeds in a bowl. Set aside.",
  "Fry curry paste in coconut oil 2 mins. Add mushrooms and edamame; stir-fry 4–5 mins.",
  "Whisk peanut butter, sriracha and lime for sauce.",
  "Spoon mushroom mix into lettuce cups. Drizzle both dressings over.",
],
free:false,adaptations:[{orig:"Soy sauce",swap:"Tamari — certified GF"}],
gfCheck:["Tamari — Kikkoman GF","Curry paste — Thai Taste or Bart GF"],
tags:["quick","family"],note:""},

{id:"thaiRedVegCurry",name:"Thai Red Vegetable Curry",cycle:1,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"2 tsp",n:"coconut oil"},
  {q:"4 tsp",n:"Thai red curry paste",gf:true},
  {q:"200g",n:"baby aubergines, quartered"},
  {q:"1",n:"red onion, chopped"},
  {q:"1",n:"red chilli, finely chopped"},
  {q:"190ml",n:"full-fat coconut milk"},
  {q:"140g",n:"mangetout"},
  {q:"240g",n:"smoked tofu, diced"},
  {q:"1 tsp",n:"brown sugar"},
  {q:"juice of 1",n:"lime"},
  {q:"small bunch",n:"fresh coriander"},
],
method:[
  "Fry curry paste in coconut oil 2 mins. Add aubergine, onion, chilli; fry 1 min.",
  "Pour in coconut milk and a splash of water. Simmer 4–5 mins.",
  "Add mangetout and tofu. Cook 3 mins. Finish with lime and coriander.",
],
free:false,adaptations:[],
gfCheck:["Curry paste — Thai Taste ✓ or Bart ✓"],
tags:["batch","family"],note:"Serve over rice. Makes 2 portions."},

{id:"appleBircherMuesli",name:"Apple Bircher Muesli",cycle:1,mealTypes:["breakfast","refuel"],prep:5,cook:0,
ingredients:[
  {q:"70g",n:"certified GF rolled oats",gf:true},
  {q:"50g",n:"GF vanilla protein powder",gf:true},
  {q:"30g",n:"dried cranberries or raisins"},
  {q:"large pinch",n:"ground cinnamon"},
  {q:"160ml",n:"fresh apple juice"},
  {q:"2",n:"apples, cored and grated"},
  {q:"2 tsp",n:"ground flaxseed"},
  {q:"2 tbsp",n:"coconut yoghurt"},
  {q:"20g",n:"pumpkin seeds"},
],
method:[
  "Combine oats, protein powder, cranberries and cinnamon. Stir in apple juice; divide into two jars. Cover and refrigerate overnight.",
  "The next morning, stir through grated apple, flaxseed and coconut yoghurt.",
  "Scatter over pumpkin seeds and serve cold.",
],
free:false,adaptations:[
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin or Nuzest GF"],
tags:["batch","otg"],note:"Prep the night before. Keeps in fridge up to 3 days. Makes 2 portions."},

{id:"coconutGranola",name:"Low-carb Coconut Granola",cycle:1,mealTypes:["breakfast"],prep:10,cook:20,
ingredients:[
  {q:"145g",n:"certified GF rolled oats",gf:true},
  {q:"90g",n:"mixed seeds (pumpkin, sunflower, sesame)"},
  {q:"90g",n:"coconut chips"},
  {q:"110g",n:"unsweetened apple sauce"},
  {q:"45g",n:"coconut oil, melted"},
  {q:"50g",n:"maple syrup or honey"},
  {q:"pinch",n:"salt"},
  {q:"100g",n:"raisins"},
  {q:"100g",n:"dried apricots, roughly chopped"},
  {q:"70g per serving",n:"coconut yoghurt (to serve)"},
],
method:[
  "Preheat oven to 160°C. Combine oats, seeds and coconut chips in a large bowl.",
  "Stir together apple sauce, coconut oil, sweetener and salt; pour over dry ingredients and toss to coat.",
  "Spread on a large roasting tray; bake 20 mins, stirring occasionally, until golden and crisp.",
  "Stir in dried fruit; cool completely. Serve with coconut yoghurt.",
],
free:false,adaptations:[
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:["Oats — certified GF only (Nairn's or Bob's Red Mill)"],
tags:["batch","otg"],note:"Makes 7 portions. Store dry granola in an airtight container up to 3 weeks; add coconut yoghurt to serve."},
]
