// Cycle 2 recipes (32: 20 core + 12 adapted)
[
{id:"spicedBerryPorridge",name:"GF Spiced Berry Porridge",cycle:2,mealTypes:["breakfast","refuel"],prep:5,cook:10,
ingredients:[
  {q:"100g",n:"certified GF rolled oats",gf:true},
  {q:"600ml",n:"full-fat coconut milk"},
  {q:"200g",n:"mixed berries"},
  {q:"2 tsp",n:"mixed spice"},
  {q:"2 tbsp",n:"maple syrup"},
  {q:"100g",n:"coconut yoghurt"},
],
method:[
  "Simmer coconut milk. Stir in oats and spice; cook 5 mins.",
  "Add berries; cook 2 mins. Sweeten with maple syrup.",
  "Divide into two bowls. Top with coconut yoghurt.",
],
free:false,adaptations:[{orig:"Regular oats + dairy milk",swap:"Certified GF oats + coconut milk"}],
gfCheck:["Oats — certified GF only (Nairn's or Bob's Red Mill)"],
tags:["batch","quick"],note:""},

{id:"gogoGreenSmoothie",name:"Go-Go Green Smoothie",cycle:2,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"60g",n:"almond butter"},
  {q:"2 large handfuls",n:"baby spinach"},
  {q:"60g",n:"GF vanilla protein powder",gf:true},
  {q:"2 large",n:"apples, cored and roughly chopped"},
  {q:"40g",n:"ground flaxseed"},
  {q:"480ml",n:"coconut water"},
  {q:"handful",n:"ice"},
],
method:["Blend all ingredients until smooth. Pour into two glasses."],
free:false,adaptations:[{orig:"Almond butter",swap:"Tahini or pumpkin seeds for nut-free"}],
gfCheck:["Protein powder — Pulsin or Nuzest GF"],
tags:["quick","otg"],note:"Naturally DF and EF. Makes 2 portions."},

{id:"mixedBeanChilli",name:"Mixed Bean Chilli",cycle:2,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"2",n:"red chillies, deseeded"},
  {q:"2 tsp",n:"ground cumin"},
  {q:"4 tsp each",n:"tomato purée, chipotle paste",gf:true},
  {q:"290g",n:"tinned chopped tomatoes"},
  {q:"400g",n:"tinned mixed beans, drained"},
  {q:"1",n:"GF stock cube in 300ml water",gf:true},
  {q:"80ml",n:"coconut cream"},
  {q:"½",n:"avocado, sliced"},
  {q:"juice of 1",n:"lime"},
  {q:"small bunch",n:"coriander"},
  {q:"130g per portion",n:"cooked rice"},
],
method:[
  "Fry onion 5 mins. Add garlic and chilli 2 mins. Add cumin, purée, chipotle 1 min.",
  "Add tomatoes, beans and stock. Simmer 15 mins. Season.",
  "Drizzle coconut cream. Top with avocado, lime and coriander. Serve with rice.",
],
free:false,adaptations:[
  {orig:"Soured cream",swap:"Coconut cream"},
  {orig:"Cheddar",swap:"Omitted — avocado adds richness"},
],
gfCheck:["Chipotle paste — check label","Stock cube — Kallo GF"],
tags:["batch","family"],note:"Carb-rich refuel — serve with rice. Makes 2 portions."},

{id:"roastedVegQuinoa",name:"Roasted Vegetable & Quinoa Bowl",cycle:2,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"2",n:"courgettes, cut into chunks"},
  {q:"1 large",n:"aubergine, cut into chunks"},
  {q:"1 large",n:"red onion, cut into wedges"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"1 tsp",n:"dried oregano"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"60g",n:"tinned chickpeas, drained"},
  {q:"160g",n:"quinoa"},
  {q:"1",n:"GF vegetable stock cube in 320ml water",gf:true},
  {q:"2",n:"tomatoes, diced"},
  {q:"2 tbsp",n:"red wine vinegar"},
  {q:"30g",n:"toasted pine nuts"},
  {q:"large bunch",n:"fresh basil, torn"},
],
method:[
  "Preheat oven to 200°C. Toss vegetables, garlic, oregano, oil and chickpeas; season. Spread on tray; roast 20 mins.",
  "Bring stock to the boil, add quinoa, cover and simmer 15 mins. Drain any excess liquid.",
  "Combine roasted veg with quinoa, tomatoes, vinegar, pine nuts and basil. Toss and serve.",
],
free:false,adaptations:[
  {orig:"Couscous (not GF)",swap:"Quinoa"},
  {orig:"Feta",swap:"Toasted pine nuts"},
],
gfCheck:["Stock cube — Kallo GF or Marigold GF"],
tags:["batch","otg"],note:"Great for lunchboxes. Makes 2 portions."},

{id:"thaiCarrotSoup",name:"Thai Carrot Soup",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"1 tbsp",n:"coconut oil"},
  {q:"4",n:"carrots, grated"},
  {q:"1",n:"red onion, sliced"},
  {q:"1",n:"red chilli, sliced"},
  {q:"2 sticks",n:"lemongrass, finely chopped"},
  {q:"2 tsp",n:"ground turmeric"},
  {q:"180ml",n:"full-fat coconut milk"},
  {q:"400ml",n:"water"},
  {q:"200g",n:"silken tofu"},
  {q:"juice of 1",n:"lime"},
  {q:"small bunch",n:"coriander"},
],
method:[
  "Fry carrots in coconut oil 3–4 mins. Add onion, chilli, lemongrass 2 mins.",
  "Add turmeric, coconut milk and water. Bring to boil; simmer 10 mins.",
  "Blend with silken tofu until smooth. Stir in lime and season.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","family"],note:"Naturally GF, DF and EF. Makes 2 portions."},

{id:"carrotCakeSmoothie",name:"Carrot Cake Smoothie",cycle:2,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"2 medium",n:"carrots, roughly chopped"},
  {q:"100g",n:"certified GF rolled oats",gf:true},
  {q:"600ml",n:"full-fat coconut milk"},
  {q:"4 tbsp",n:"almond butter"},
  {q:"2 tsp",n:"mixed spice"},
  {q:"4",n:"Medjool dates, pitted"},
  {q:"handful",n:"ice"},
],
method:["Blend everything until smooth. Pour into two glasses."],
free:false,adaptations:[{orig:"Dairy milk + regular oats",swap:"Coconut milk + certified GF oats"}],
gfCheck:["Oats — certified GF only"],
tags:["quick","otg"],note:""},

{id:"splitPeaSpinachSoup",name:"Split Pea & Spinach Soup",cycle:2,mealTypes:["lunch","dinner"],prep:5,cook:35,
ingredients:[
  {q:"200g",n:"dried green split peas"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"40g",n:"chia seeds"},
  {q:"2",n:"GF vegetable stock cubes",gf:true},
  {q:"large handful",n:"baby spinach"},
  {q:"40g",n:"pumpkin seeds"},
  {q:"juice of 1",n:"lemon"},
],
method:[
  "Tip split peas into pan with garlic, chia seeds and stock cubes. Cover with boiling water.",
  "Simmer covered 30 mins, stirring occasionally. Add spinach 2 mins.",
  "Blend roughly. Season with lemon, salt and pepper. Top with pumpkin seeds.",
],
free:false,adaptations:[{orig:"Feta",swap:"Pumpkin seeds for crunch"}],
gfCheck:["Stock cubes — Kallo GF or Marigold GF"],
tags:["batch","otg"],note:""},

{id:"gfTomatoBeanPasta",name:"GF Tomato & Bean Pasta",cycle:2,mealTypes:["refuel"],prep:5,cook:20,
ingredients:[
  {q:"160g",n:"GF pasta (penne or fusilli)",gf:true},
  {q:"1 tbsp",n:"olive oil"},
  {q:"3 cloves",n:"garlic, sliced"},
  {q:"400g",n:"tinned chopped tomatoes"},
  {q:"240g",n:"tinned cannellini beans, drained"},
  {q:"2 tsp",n:"dried oregano"},
  {q:"large handful",n:"baby spinach"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"small bunch",n:"fresh basil"},
],
method:[
  "Cook GF pasta per pack. Drain.",
  "Fry garlic 1 min. Add tomatoes and oregano; simmer 8 mins.",
  "Add beans and spinach 2 mins. Stir in nutritional yeast.",
  "Toss with pasta and basil.",
],
free:false,adaptations:[
  {orig:"Regular pasta",swap:"GF pasta — Doves Farm or Barilla GF"},
  {orig:"Parmesan",swap:"Nutritional yeast"},
],
gfCheck:["GF pasta — Doves Farm ✓, Barilla GF ✓"],
tags:["batch","quick"],note:"Carb-rich refuel — pasta and beans for post-workout energy. Makes 2 portions."},

{id:"cauliflowerSteaksTahini",name:"Cauliflower Steaks with Tahini Dressing",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"4 thick slices",n:"cauliflower (approx 390g)"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"1 tbsp",n:"ras el hanout"},
  {q:"40g",n:"tahini"},
  {q:"120g",n:"soya yoghurt"},
  {q:"juice of 1",n:"lemon"},
  {q:"1",n:"red chilli, finely chopped"},
  {q:"40g",n:"toasted pine nuts"},
  {q:"70g",n:"pomegranate seeds"},
  {q:"large bunch",n:"flat-leaf parsley, chopped"},
],
method:[
  "Preheat oven to 220°C. Brush cauliflower with oil, rub with ras el hanout, season. Lay on lined tray; roast 20 mins.",
  "Whisk tahini, soya yoghurt, lemon juice, chilli and a splash of water until smooth dressing.",
  "Plate steaks, drizzle with dressing and top with pine nuts, pomegranate and parsley.",
],
free:false,adaptations:[{orig:"Greek yoghurt",swap:"Soya yoghurt"}],
gfCheck:[],tags:["family"],note:"Bold Middle Eastern flavours. Makes 2 portions."},

{id:"chickpeaSaladBowl",name:"Chickpea Salad Bowl",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:0,
ingredients:[
  {q:"400g",n:"tinned chickpeas, drained"},
  {q:"½",n:"cucumber, diced"},
  {q:"handful",n:"cherry tomatoes, halved"},
  {q:"½",n:"red onion, finely sliced"},
  {q:"large bunch",n:"parsley and coriander, chopped"},
  {q:"juice of 1",n:"lemon"},
  {q:"2 tbsp",n:"olive oil"},
  {q:"1 tsp",n:"ground cumin"},
  {q:"1",n:"avocado, sliced"},
],
method:[
  "Combine all ingredients except avocado. Whisk lemon, oil and cumin; season.",
  "Pour dressing over and toss. Divide into two portions.",
  "Top with avocado just before serving.",
],
free:true,adaptations:[],gfCheck:[],
tags:["quick","otg"],note:"Add avocado just before eating to prevent browning. Makes 2 portions."},

{id:"mushroomGingerCashewStirFry",name:"Mushroom, Ginger & Cashew Stir-fry",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"1 tbsp",n:"coconut oil"},
  {q:"310g",n:"chestnut mushrooms, sliced"},
  {q:"1 small",n:"white onion, finely sliced"},
  {q:"2",n:"red chillies, finely chopped"},
  {q:"30g",n:"fresh ginger, peeled and grated"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"1",n:"red pepper, cut into chunks"},
  {q:"80g",n:"baby sweetcorn, halved"},
  {q:"80g",n:"edamame beans (soya beans)"},
  {q:"70g",n:"unsalted roasted cashews, crushed"},
  {q:"40g",n:"vegetarian hoisin sauce",gf:true},
],
method:[
  "Heat oil in wok over high heat. Fry mushrooms 3–4 mins until browned. Remove with slotted spoon.",
  "Fry onion, chilli, ginger and garlic 2 mins. Add pepper, sweetcorn and edamame; fry 2 mins.",
  "Splash in water; cook 2–3 mins until veg softens. Return mushrooms to wok.",
  "Add cashews and hoisin; toss to combine and serve.",
],
free:false,adaptations:[{orig:"Oyster sauce",swap:"Vegetarian hoisin — check GF label"}],
gfCheck:["Hoisin sauce — Lee Kum Kee Vegetarian is GF"],
tags:["family"],note:"Serve over rice. Makes 2 portions."},

{id:"creamyTomatoPasta",name:"Creamy Tomato Pasta",cycle:2,mealTypes:["lunch","dinner"],prep:15,cook:20,
ingredients:[
  {q:"70g",n:"unsalted roasted cashews"},
  {q:"2 tsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"1 tbsp",n:"tomato purée"},
  {q:"290g",n:"tinned chopped tomatoes"},
  {q:"100g",n:"GF red lentil pasta",gf:true},
  {q:"large bunch",n:"fresh basil, leaves torn"},
],
method:[
  "Soak cashews in just-boiling water 15 mins. Blend with soaking liquid until smooth cream.",
  "Heat oil, fry garlic 1 min. Add tomato purée and tomatoes; simmer 10 mins until thickened.",
  "Stir in cashew cream; cook 2–3 mins. Season well.",
  "Cook pasta per packet instructions, drain, stir into sauce with basil.",
],
free:true,adaptations:[],gfCheck:[],
tags:["family"],note:"Cashew cream replaces dairy completely. GF lentil pasta is naturally protein-rich. Makes 2 portions."},

{id:"chilliTofu",name:"Chilli Tofu",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"4 tsp",n:"white wine vinegar"},
  {q:"4 tsp",n:"tomato ketchup"},
  {q:"4 tsp",n:"tamari (GF soy sauce)",gf:true},
  {q:"4 tsp",n:"sriracha or chilli sauce"},
  {q:"1 tsp",n:"cornflour"},
  {q:"2 tsp",n:"coconut oil"},
  {q:"1",n:"onion, cut into chunks"},
  {q:"1",n:"green pepper, cut into chunks"},
  {q:"200g",n:"firm tofu, drained and diced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"2",n:"green chillies, finely chopped"},
],
method:[
  "Whisk vinegar, ketchup, tamari, sriracha and cornflour together. Season with black pepper.",
  "Heat oil in a wok over high heat until smoking. Fry onion, pepper and tofu 3–4 mins.",
  "Add garlic and chilli; fry 2 mins. Pour in sauce; bubble 2 mins until glossy. Serve.",
],
free:false,adaptations:[
  {orig:"Paneer",swap:"Firm tofu — press and pat dry well before frying"},
  {orig:"Dark soy sauce",swap:"Tamari — certified GF"},
],
gfCheck:["Tamari — Kikkoman GF or Clearspring"],
tags:["quick"],note:"Serve over rice. Makes 2 portions."},

{id:"spicyBeanNachos",name:"Spicy Bean Nachos",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:25,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"1 tsp",n:"ground cumin"},
  {q:"1 tsp",n:"chilli powder or smoked paprika"},
  {q:"190g",n:"tinned chopped tomatoes"},
  {q:"120g",n:"tinned kidney beans, drained"},
  {q:"100g",n:"GF corn tortilla chips",gf:true},
  {q:"1",n:"avocado, sliced"},
  {q:"30g",n:"sliced jalapeños, drained"},
  {q:"60ml",n:"coconut yoghurt"},
  {q:"small bunch",n:"coriander, chopped"},
],
method:[
  "Heat oil; fry onion and garlic 4–5 mins. Add spices; fry 1 min.",
  "Pour in tomatoes and a splash of water. Simmer 10 mins. Add beans; cook 5 mins.",
  "Arrange tortilla chips on plates, spoon over bean chilli. Top with avocado, jalapeños, coconut yoghurt and coriander.",
],
free:false,adaptations:[
  {orig:"Flour tortillas",swap:"GF corn tortilla chips — Tyrrells or Siete"},
  {orig:"Cheddar + soured cream",swap:"Avocado + coconut yoghurt"},
],
gfCheck:["Corn tortilla chips — check GF labelling"],
tags:["family"],note:"Great sharing plate. Makes 2 portions."},

{id:"cocoChocolateSmoothie",name:"Coconut & Chocolate Smoothie",cycle:2,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"2 medium",n:"bananas"},
  {q:"390ml",n:"unsweetened soya or almond milk"},
  {q:"230ml",n:"full-fat tinned coconut milk"},
  {q:"150g",n:"coconut yoghurt"},
  {q:"40g",n:"GF chocolate or vanilla protein powder",gf:true},
  {q:"60g",n:"ground flaxseed"},
  {q:"4 tsp",n:"raw cacao powder"},
  {q:"handful",n:"ice"},
],
method:["Blend all ingredients until smooth. Pour into two glasses."],
free:false,adaptations:[{orig:"Greek/natural yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"}],
gfCheck:["Protein powder — Pulsin or Nuzest GF"],
tags:["quick","otg"],note:"Rich, chocolatey breakfast smoothie. Makes 2 portions."},

{id:"peaSpinachRisotto",name:"Pea & Spinach Risotto",cycle:2,mealTypes:["refuel"],prep:5,cook:25,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"white onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"130g",n:"risotto rice"},
  {q:"2",n:"GF vegetable stock cubes in 800ml boiling water",gf:true},
  {q:"2 large handfuls",n:"baby leaf spinach"},
  {q:"230g",n:"frozen peas, defrosted"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"handful",n:"pea shoots or rocket, to serve"},
],
method:[
  "Heat oil; fry onion and garlic 3–4 mins until soft. Add rice; fry 1 min.",
  "Add stock a ladleful at a time, stirring until absorbed, for about 10 mins.",
  "When ~200ml stock remains, blend it with the spinach and half the peas until smooth.",
  "Pour blended mixture into the pan. Stir in remaining peas; cook 2 mins.",
  "Stir in nutritional yeast; season well. Serve topped with pea shoots.",
],
free:false,adaptations:[{orig:"Goat's cheese",swap:"Nutritional yeast"}],
gfCheck:["Stock cubes — Kallo GF or Marigold GF"],
tags:["batch"],note:"Rice and peas provide good post-workout carbohydrate. Makes 2 portions."},

{id:"creamyLeekMushroomPasta",name:"Creamy Leek & Mushroom Pasta",cycle:2,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"60g",n:"unsalted cashews"},
  {q:"160g",n:"GF pasta (pappardelle or penne)",gf:true},
  {q:"2 tsp",n:"olive oil"},
  {q:"310g",n:"leeks, finely sliced"},
  {q:"100g",n:"chestnut mushrooms, sliced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Soak cashews in just-boiling water 15 mins. Blend with soaking liquid until smooth.",
  "Heat oil; fry leeks gently 10 mins until soft and beginning to caramelise. Add mushrooms and garlic; fry 3–4 mins.",
  "Stir in cashew cream and nutritional yeast; season well.",
  "Cook GF pasta per packet. Drain, reserving pasta water. Toss with leek sauce, loosening with pasta water as needed.",
],
free:false,adaptations:[
  {orig:"Wheat pasta",swap:"GF pasta — Doves Farm or Barilla GF"},
  {orig:"Low-fat cream cheese",swap:"Cashew cream (60g cashews soaked + blended)"},
  {orig:"Hard cheese",swap:"Nutritional yeast"},
],
gfCheck:["GF pasta — Doves Farm ✓, Barilla GF ✓"],
tags:["batch","quick"],note:"Rich, comforting carb refuel. Makes 2 portions."},

{id:"blackBeanQuesadillas",name:"Black Bean Quesadillas",cycle:2,mealTypes:["refuel"],prep:5,cook:10,
ingredients:[
  {q:"200g",n:"tinned black beans, drained"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"ground cumin"},
  {q:"2",n:"red chillies, finely chopped"},
  {q:"juice of 2",n:"limes"},
  {q:"80g",n:"spring onions, finely chopped"},
  {q:"small bunch",n:"coriander, chopped"},
  {q:"4 small",n:"GF corn tortillas",gf:true},
],
method:[
  "Combine beans, nutritional yeast, cumin, chilli, lime, spring onions and coriander; roughly mash with a fork. Season.",
  "Spread mixture over 2 tortillas; top each with a second tortilla and press together firmly.",
  "Heat a dry frying pan over medium heat. Cook each quesadilla 3–4 mins per side until golden and crisp. Slice into wedges.",
],
free:false,adaptations:[
  {orig:"Mature cheddar",swap:"Nutritional yeast"},
  {orig:"Flour tortillas",swap:"GF corn tortillas — Old El Paso GF or Mission GF"},
],
gfCheck:["Corn tortillas — check GF labelling (Old El Paso GF ✓, Mission GF ✓)"],
tags:["quick","family"],note:"Fast high-protein post-workout refuel. Makes 2 portions."},

{id:"creamyMushroomsToast",name:"Creamy Mushrooms on Toast",cycle:2,mealTypes:["breakfast"],prep:5,cook:15,
ingredients:[
  {q:"60g",n:"unsalted cashews"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"480g",n:"chestnut or mixed mushrooms, thickly sliced"},
  {q:"160g",n:"firm tofu, drained"},
  {q:"1 tbsp",n:"Dijon mustard"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"2 thick slices",n:"GF bread, toasted",gf:true},
  {q:"small bunch",n:"parsley, chopped"},
],
method:[
  "Soak cashews in just-boiling water 15 mins; blend with a splash of soaking liquid until smooth.",
  "Heat coconut oil over high heat; fry mushrooms 5–6 mins until golden.",
  "Blend tofu, mustard and cashew cream until completely smooth.",
  "Off the heat, pour tofu cream and nutritional yeast into mushroom pan; toss to coat. Season.",
  "Spoon over toasted GF bread; scatter parsley and serve.",
],
free:false,adaptations:[
  {orig:"Butter",swap:"Coconut oil"},
  {orig:"Crème fraîche",swap:"Cashew cream (60g cashews soaked + blended)"},
  {orig:"Hard cheese",swap:"Nutritional yeast"},
  {orig:"Wholemeal bread",swap:"GF bread — Warburtons GF or Genius"},
],
gfCheck:["GF bread — check labelled GF, not just wheat-free"],
tags:["quick","family"],note:"Satisfying rest-day breakfast. Makes 2 portions."},

{id:"veggieKorma",name:"Veggie Korma with Poppadoms",cycle:2,mealTypes:["lunch","dinner"],prep:15,cook:15,
ingredients:[
  {q:"70g",n:"unsalted roasted cashews"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"1 small",n:"red onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"40g",n:"fresh ginger, grated"},
  {q:"1 tsp",n:"chilli powder"},
  {q:"2 tsp each",n:"ground cumin, curry powder, turmeric"},
  {q:"520g",n:"tinned chickpeas, drained"},
  {q:"120g",n:"coconut yoghurt"},
  {q:"small bunch",n:"coriander, leaves chopped"},
  {q:"4",n:"rice poppadoms",gf:true},
],
method:[
  "Soak cashews in just-boiling water 10 mins; blend with soaking liquid until smooth.",
  "Heat coconut oil; fry onion 5 mins until soft. Add garlic, ginger and spices; fry 1 min.",
  "Add a splash of water, the cashew cream and chickpeas. Simmer 5–8 mins until sauce thickens.",
  "Remove from heat; stir in coconut yoghurt. Season, top with coriander. Serve with rice poppadoms.",
],
free:false,adaptations:[
  {orig:"Quorn chicken pieces (eggs + wheat)",swap:"Tinned chickpeas"},
  {orig:"Soya/Greek yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:["Rice poppadoms — check GF labelling"],
tags:["family"],note:"Mild, family-friendly curry. Serve with rice for a heartier meal. Makes 2 portions."},

// Cycle 2 adapted (12)
{id:"oatmealPancakes",name:"Overnight Oatmeal Pancakes",cycle:2,mealTypes:["refuel"],prep:10,cook:10,
ingredients:[
  {q:"80g",n:"certified GF rolled oats",gf:true},
  {q:"20g",n:"ground flaxseed"},
  {q:"20g",n:"GF vanilla protein powder",gf:true},
  {q:"pinch",n:"salt"},
  {q:"160g",n:"coconut yoghurt, plus 2 tbsp to serve"},
  {q:"2 tbsp ground flaxseed + 6 tbsp water",n:"(flax eggs — prep in morning)"},
  {q:"1 tsp",n:"GF baking powder",gf:true},
  {q:"100g",n:"blueberries"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"30g",n:"honey, plus extra to serve"},
],
method:[
  "Night before: combine oats, 20g ground flaxseed, protein powder, salt and coconut yoghurt in a bowl. Cover and refrigerate overnight.",
  "Next morning: mix 2 tbsp ground flaxseed with 6 tbsp water; rest 5 mins to form flax eggs.",
  "Beat flax eggs and baking powder into the soaked oat mixture; add a splash of water if too thick. Fold in blueberries.",
  "Melt coconut oil in a frying pan; fry large spoonfuls of batter 1–2 mins per side until golden. Serve with coconut yoghurt and honey.",
],
free:false,adaptations:[
  {orig:"Regular rolled oats",swap:"Certified GF rolled oats"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
  {orig:"1 large egg",swap:"Flax egg (1 tbsp ground flaxseed + 3 tbsp water per egg)"},
],
gfCheck:["Oats — certified GF (Nairn's ✓)","Protein powder — Pulsin or Nuzest GF ✓","Baking powder — Dr. Oetker GF ✓"],
tags:["batch"],note:"Prep the soaked oat mix the night before. Makes 2 portions."},

{id:"proteinMuffins",name:"Make-Ahead Blueberry Protein Muffins",cycle:2,mealTypes:["refuel"],prep:15,cook:25,
ingredients:[
  {q:"255g",n:"GF plain flour",gf:true},
  {q:"1½ tsp",n:"GF baking powder",gf:true},
  {q:"1½ tsp",n:"bicarbonate of soda"},
  {q:"pinch",n:"salt"},
  {q:"35g",n:"ground flaxseed"},
  {q:"2 tbsp ground flaxseed + 6 tbsp water",n:"(flax eggs)"},
  {q:"150g",n:"GF vanilla protein powder",gf:true},
  {q:"45g",n:"coconut oil, melted"},
  {q:"195ml",n:"coconut yoghurt"},
  {q:"205g",n:"ripe banana, mashed (approx 2 medium)"},
  {q:"70g",n:"honey"},
  {q:"155g",n:"blueberries, fresh or frozen"},
],
method:[
  "Preheat oven to 180°C; line a 12-hole muffin tin. Mix 2 tbsp ground flaxseed with 6 tbsp water; rest 5 mins.",
  "Sift GF flour, baking powder, bicarbonate of soda and salt into a large bowl; stir in 35g ground flaxseed.",
  "Blend flax eggs, coconut oil, coconut yoghurt, banana and honey until smooth; pour into dry ingredients and fold together.",
  "Fold in blueberries; divide between cases and bake 20–25 mins until risen and golden. Cool before eating.",
],
free:false,adaptations:[
  {orig:"Plain wheat flour",swap:"GF plain flour (Doves Farm)"},
  {orig:"2 large eggs",swap:"2 flax eggs (2 tbsp ground flaxseed + 6 tbsp water)"},
  {orig:"Reduced-fat soured cream",swap:"Coconut yoghurt"},
],
gfCheck:["GF plain flour — Doves Farm ✓","Protein powder — Pulsin or Nuzest GF ✓","Baking powder — Dr. Oetker GF ✓"],
tags:["batch","otg"],note:"Makes 12 muffins (6 servings of 2). Freeze individually wrapped without paper cases."},

{id:"hashBrownsScrambledTofu",name:"Hash Browns with Scrambled Tofu",cycle:2,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"280g",n:"potato, peeled and cut into chunks"},
  {q:"200g",n:"sweet potato, peeled and cut into chunks"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"130g",n:"spring onions, sliced"},
  {q:"2 medium",n:"courgettes, grated"},
  {q:"40g",n:"GF unflavoured protein powder",gf:true},
  {q:"salt and pepper",n:"to season"},
  {q:"300g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"1 tsp",n:"olive oil (for tofu)"},
],
method:[
  "Boil potatoes and sweet potato 8–10 mins until tender; drain and leave to steam dry completely.",
  "Fry spring onions in half the oil until soft; tip into a bowl. Finely chop cooled potatoes and add to bowl with grated courgette and protein powder; season generously. Divide into 4 portions and flatten into rounds.",
  "Fry hash browns in remaining oil 2–3 mins each side until golden.",
  "Heat 1 tsp oil in a separate pan; fry tofu with turmeric, nutritional yeast and tamari 3–4 mins until golden scrambled. Serve alongside hash browns.",
],
free:false,adaptations:[
  {orig:"Poached eggs",swap:"Scrambled tofu (turmeric + nutritional yeast + tamari)"},
],
gfCheck:["Protein powder — Pulsin GF ✓ (unflavoured)","Tamari — Kikkoman GF ✓"],
tags:["batch","family"],note:"Shape hash browns the night before; refrigerate ready to cook. Makes 2 portions."},

{id:"breakfastBurger",name:"Breakfast Burger",cycle:2,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"240g",n:"sweet potato, cut into fries"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"salt and pepper",n:"to season"},
  {q:"2 large",n:"field mushrooms"},
  {q:"200g",n:"firm tofu, crumbled"},
  {q:"¼ tsp",n:"turmeric"},
  {q:"3 tbsp",n:"nutritional yeast"},
  {q:"1 tsp",n:"tamari (GF)",gf:true},
  {q:"2",n:"GF burger buns, split and toasted",gf:true},
  {q:"4 tsp",n:"tomato ketchup",gf:true},
  {q:"4 tsp",n:"vegan mayo",gf:true},
  {q:"4 thick slices",n:"tomato"},
],
method:[
  "Preheat oven to 180°C. Roast sweet potato fries and mushrooms with oil and seasoning 15 mins until fries are cooked through and mushrooms are soft.",
  "Scatter 1 tbsp nutritional yeast over each mushroom; return to oven 5 mins until melted.",
  "Meanwhile fry tofu with turmeric, remaining nutritional yeast and tamari 3–4 mins until scrambled and golden.",
  "Spread buns with ketchup and vegan mayo; layer tomato slices, scrambled tofu and cheesy mushroom. Serve with sweet potato fries.",
],
free:false,adaptations:[
  {orig:"1 egg + 1 egg white (scrambled)",swap:"Scrambled tofu (turmeric + nutritional yeast + tamari)"},
  {orig:"Mature cheddar on mushroom",swap:"Nutritional yeast"},
  {orig:"Wheat burger bun",swap:"GF burger bun (Warburtons GF)"},
],
gfCheck:["GF burger buns — Warburtons GF ✓","Ketchup — Heinz ✓ (check label)","Vegan mayo — Hellmann's Vegan ✓","Tamari — Kikkoman GF ✓"],
tags:["family"],note:"Makes 2 portions."},

{id:"spanishTortilla",name:"Chickpea Flour Spanish Tortilla",cycle:2,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"3 medium",n:"onions, finely sliced"},
  {q:"410g",n:"new potatoes, sliced"},
  {q:"150g",n:"gram flour (chickpea flour)"},
  {q:"300ml",n:"water"},
  {q:"40g",n:"GF unflavoured protein powder",gf:true},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"½ tsp",n:"turmeric"},
  {q:"salt and pepper",n:"to season"},
  {q:"green salad",n:"to serve"},
],
method:[
  "Heat oil in a small non-stick frying pan; fry onions very gently 10 mins until soft and starting to caramelise.",
  "Boil sliced potatoes in salted water 6–8 mins until tender; drain well.",
  "Whisk gram flour, water, protein powder, nutritional yeast and turmeric to a smooth batter; season generously. Stir in onions and potatoes.",
  "Pour into the oiled pan; cook gently without stirring until almost set in the middle. Flip onto a plate then slide back; cook 3–4 mins until set with a slight wobble. Turn onto a board; cut into wedges.",
],
free:false,adaptations:[
  {orig:"2 eggs + 3 egg whites",swap:"Gram flour batter (gram flour + water + nutritional yeast + turmeric)"},
],
gfCheck:["Protein powder — Pulsin GF ✓ (unflavoured)"],
tags:["batch","family"],note:"Keeps up to 3 days; delicious served cold. Makes 2–3 portions."},

{id:"almondHoneyPancakes",name:"Almond & Honey Pancakes",cycle:2,mealTypes:["breakfast"],prep:5,cook:10,
ingredients:[
  {q:"60g",n:"ground almonds"},
  {q:"40g",n:"certified GF rolled oats",gf:true},
  {q:"1 tsp",n:"GF baking powder",gf:true},
  {q:"2 tbsp",n:"ground flaxseed"},
  {q:"6 tbsp",n:"water (for flax eggs)"},
  {q:"100ml",n:"unsweetened almond milk"},
  {q:"2 tbsp",n:"honey"},
  {q:"pinch",n:"salt"},
  {q:"1 tsp",n:"coconut oil"},
  {q:"2 tbsp",n:"coconut yoghurt"},
  {q:"150g",n:"blueberries"},
],
method:[
  "Mix ground flaxseed with water; rest 5 mins to form flax eggs.",
  "Blend ground almonds, oats, baking powder, flax eggs, almond milk, 1 tbsp honey and salt until smooth.",
  "Melt coconut oil in a non-stick pan; fry large spoonfuls of batter 1 min per side until bubbles form and edges are set.",
  "Stack pancakes; top with coconut yoghurt, drizzle over remaining honey and serve with blueberries.",
],
free:false,adaptations:[
  {orig:"1 medium egg",swap:"Flax egg (1 tbsp ground flaxseed + 3 tbsp water)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
  {orig:"Rolled oats",swap:"Certified GF rolled oats"},
],
gfCheck:["Oats — certified GF (Nairn's ✓)","Baking powder — Dr. Oetker GF ✓"],
tags:["quick","family"],note:"Swap ground almonds for desiccated coconut for a nut-free version. Makes 2 portions."},

{id:"eggsFlorentine",name:"Florentine-style Tofu with Creamy Sauce",cycle:2,mealTypes:["breakfast"],prep:10,cook:15,
ingredients:[
  {q:"470g",n:"baby leaf spinach"},
  {q:"pinch",n:"freshly grated nutmeg"},
  {q:"salt and pepper",n:"to season"},
  {q:"120g",n:"coconut yoghurt"},
  {q:"1 tsp",n:"Dijon mustard"},
  {q:"2 tsp",n:"vegan butter or coconut oil"},
  {q:"juice of ½",n:"lemon"},
  {q:"½ tsp",n:"turmeric (for colour)"},
  {q:"400g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric (for tofu)"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"1 tsp",n:"olive oil"},
  {q:"2",n:"GF English muffins, split and toasted",gf:true},
],
method:[
  "Wilt spinach in a splash of water; drain thoroughly and squeeze out all moisture. Season with nutmeg, salt and pepper.",
  "Whisk coconut yoghurt, mustard, vegan butter, lemon juice and ½ tsp turmeric together in a small pan; warm gently over low heat 2–3 mins until slightly thickened.",
  "Heat olive oil in a frying pan; fry tofu with turmeric, nutritional yeast and tamari 3–4 mins until golden scrambled.",
  "Top each GF muffin half with spinach and tofu scramble; spoon creamy sauce over and serve.",
],
free:false,adaptations:[
  {orig:"3 poached eggs",swap:"Scrambled tofu (turmeric + nutritional yeast + tamari)"},
  {orig:"Egg yolk hollandaise",swap:"Coconut yoghurt + Dijon + lemon + turmeric sauce"},
  {orig:"Wholemeal wheat muffin",swap:"GF English muffin (Genius GF or similar)"},
],
gfCheck:["GF muffins — Genius GF ✓ or similar (check label)","Tamari — Kikkoman GF ✓"],
tags:["quick","family"],note:"Makes 2 portions."},

{id:"breakfastBurrito",name:"Breakfast Burrito",cycle:2,mealTypes:["breakfast"],prep:10,cook:15,
ingredients:[
  {q:"4 tsp",n:"olive oil"},
  {q:"1 small",n:"red onion, sliced"},
  {q:"1",n:"red pepper, sliced"},
  {q:"200g",n:"tinned black beans, drained"},
  {q:"2",n:"GF corn tortillas",gf:true},
  {q:"300g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"60g",n:"Violife feta-style, crumbled",gf:true},
  {q:"small bunch",n:"coriander, chopped"},
  {q:"dash",n:"chilli sauce (optional)",gf:true},
],
method:[
  "Heat half the oil in a pan; fry onion and pepper 5 mins until soft. Add beans; cook 2 mins to heat through. Spoon onto tortillas.",
  "Wipe pan; heat remaining oil. Fry tofu with turmeric, nutritional yeast and tamari 3–4 mins until scrambled and golden.",
  "Spoon tofu scramble over bean mixture. Crumble over Violife feta; top with coriander and chilli sauce.",
  "Roll tortillas tightly and serve.",
],
free:false,adaptations:[
  {orig:"2 beaten eggs (scrambled)",swap:"Scrambled tofu (turmeric + nutritional yeast + tamari)"},
  {orig:"Feta",swap:"Violife feta-style"},
  {orig:"Wholewheat tortilla",swap:"GF corn tortilla (Old El Paso GF or Mission GF)"},
],
gfCheck:["GF corn tortillas — Old El Paso GF ✓ or Mission GF ✓","Violife feta-style — GF ✓ (check label)","Tamari — Kikkoman GF ✓"],
tags:["quick","otg"],note:"Makes 2 portions."},

{id:"roastedPepperMushroomFrittata",name:"Roasted Pepper & Mushroom Chickpea Frittata",cycle:2,mealTypes:["lunch","dinner"],prep:15,cook:25,
ingredients:[
  {q:"1 large",n:"red pepper, cut into chunks"},
  {q:"2 tsp",n:"olive oil"},
  {q:"salt and pepper",n:"to season"},
  {q:"160g",n:"mushrooms, thickly sliced"},
  {q:"170g",n:"cooked new potatoes, sliced"},
  {q:"120g",n:"gram flour (chickpea flour)"},
  {q:"240ml",n:"water"},
  {q:"2 tbsp",n:"nutritional yeast"},
  {q:"½ tsp",n:"turmeric"},
  {q:"small bunch",n:"chives, finely chopped"},
  {q:"90g",n:"Violife feta-style, crumbled",gf:true},
  {q:"green salad",n:"to serve"},
],
method:[
  "Preheat oven to 220°C; preheat grill. Roast peppers with half the oil 15 mins until soft.",
  "Heat remaining oil in a non-stick ovenproof pan; fry mushrooms 5 mins until golden. Add peppers and potatoes; arrange in an even layer.",
  "Whisk gram flour, water, nutritional yeast, turmeric and chives to a smooth batter; season. Pour over vegetables; cook over medium heat until almost set.",
  "Crumble Violife feta over the top; grill 3 mins until golden. Slide onto a board; cut into wedges.",
],
free:false,adaptations:[
  {orig:"8 eggs + 4 egg whites",swap:"Chickpea flour batter (gram flour + water + nutritional yeast + turmeric)"},
  {orig:"Feta",swap:"Violife feta-style"},
],
gfCheck:["Violife feta-style — GF ✓ (check label)"],
tags:["batch"],note:"Original serves 3; scaled to 2 here. Keeps 3 days in fridge. Makes 2 portions."},

{id:"beanFritters",name:"Bean Fritters with Mint Yoghurt",cycle:2,mealTypes:["lunch","dinner"],prep:10,cook:10,
ingredients:[
  {q:"80g",n:"gram flour (chickpea flour)"},
  {q:"60ml",n:"water or aquafaba"},
  {q:"20g",n:"GF unflavoured protein powder",gf:true},
  {q:"large pinch",n:"smoked paprika or chilli powder"},
  {q:"200g",n:"edamame beans (soya beans)"},
  {q:"80g",n:"spring onions, finely chopped"},
  {q:"salt and pepper",n:"to season"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"small bunch",n:"mint, chopped"},
  {q:"120g",n:"coconut yoghurt"},
  {q:"green salad",n:"to serve"},
],
method:[
  "Blend gram flour, water, protein powder, paprika, edamame beans and spring onions to a rough paste, leaving some texture.",
  "Heat oil in a frying pan over medium-high heat; drop large spoonfuls into the pan. Fry 2 mins each side until golden.",
  "Mix mint into coconut yoghurt; serve alongside fritters and salad.",
],
free:false,adaptations:[
  {orig:"1 egg + 1 egg white",swap:"Extra gram flour + water (chickpea flour binds naturally)"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:["Protein powder — Pulsin GF ✓ (unflavoured)"],
tags:["quick","otg"],note:"Edamame beans are in the supermarket freezer aisle. Makes 2 portions."},

{id:"halloumiBurger",name:"Vegan Halloumi Burger with Chilli & Mint",cycle:2,mealTypes:["lunch","dinner"],prep:5,cook:10,
ingredients:[
  {q:"1",n:"red pepper, deseeded and quartered"},
  {q:"2 tsp",n:"olive oil"},
  {q:"salt and pepper",n:"to season"},
  {q:"160g",n:"Violife halloumi-style, sliced",gf:true},
  {q:"small bunch",n:"mint, chopped"},
  {q:"2",n:"red chillies, deseeded and finely chopped"},
  {q:"2",n:"GF burger buns, split and toasted",gf:true},
  {q:"60g",n:"vegan mayo",gf:true},
  {q:"4 leaves",n:"baby gem lettuce"},
],
method:[
  "Heat a griddle pan over high heat. Brush pepper with half the oil, season and griddle 2 mins each side until soft. Remove.",
  "Toss Violife halloumi in remaining oil with mint and chilli; griddle 1 min each side until golden and marked.",
  "Spread inside of buns with vegan mayo; layer pepper, halloumi and lettuce.",
],
free:false,adaptations:[
  {orig:"Dairy halloumi",swap:"Violife halloumi-style"},
  {orig:"Wheat burger bun",swap:"GF burger bun (Warburtons GF or Genius)"},
  {orig:"Light mayonnaise",swap:"Vegan mayo"},
],
gfCheck:["Violife halloumi-style — GF ✓ (check label)","GF burger buns — Warburtons GF ✓ or Genius GF ✓","Vegan mayo — Hellmann's Vegan ✓"],
tags:["quick","family"],note:"Makes 2 portions."},

{id:"lowCarbCottagePie",name:"Low-carb Lentil Cottage Pie",cycle:2,mealTypes:["lunch","dinner"],prep:15,cook:30,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"2",n:"onions, finely chopped"},
  {q:"2",n:"carrots, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"2×400g tins",n:"green or brown lentils, drained"},
  {q:"30g",n:"tomato purée"},
  {q:"390g",n:"tinned chopped tomatoes"},
  {q:"2 tsp",n:"GF Worcestershire sauce or tamari (GF)",gf:true},
  {q:"2 tbsp",n:"vegan butter"},
  {q:"580g",n:"cauliflower florets"},
  {q:"290ml",n:"GF oat milk or full-fat coconut milk",gf:true},
  {q:"30g",n:"GF breadcrumbs",gf:true},
  {q:"8 tbsp",n:"nutritional yeast"},
  {q:"green salad",n:"to serve"},
],
method:[
  "Heat oil; cook onions, carrots and garlic 5 mins. Increase heat, add lentils and fry 2 mins. Stir in tomato purée 1 min; pour in tomatoes and Worcestershire sauce. Simmer 15 mins until thickened; season.",
  "Melt vegan butter in a saucepan; add cauliflower and fry 3–4 mins. Pour over milk; cover and cook 15 mins until soft. Blend with half the nutritional yeast until smooth. Preheat grill.",
  "Pour lentil mixture into an ovenproof dish; spoon cauliflower mash over and rough with a fork. Scatter remaining nutritional yeast and GF breadcrumbs; grill 10 mins until golden.",
],
free:false,adaptations:[
  {orig:"700g Quorn mince",swap:"2×400g tins green/brown lentils — Quorn contains egg white and wheat"},
  {orig:"Butter",swap:"Vegan butter (Naturli or Flora Plant)"},
  {orig:"Skimmed milk",swap:"GF oat milk or full-fat coconut milk"},
  {orig:"Cheddar + hard cheese",swap:"Nutritional yeast"},
],
gfCheck:["Lea & Perrins Worcestershire — check current GF status","GF breadcrumbs — Orgran ✓","Oat milk — GF certified (if using)"],
tags:["batch","family"],note:"Makes 4 portions. Chill overnight before slicing; freeze individual portions."},
]
