// Cycle 3 recipes (30: 23 core + 7 adapted)
[
{id:"chocolateProteinPorridge",name:"Chocolate GF Protein Porridge",cycle:3,mealTypes:["breakfast","refuel"],prep:5,cook:10,
ingredients:[
  {q:"100g",n:"certified GF rolled oats",gf:true},
  {q:"600ml",n:"full-fat coconut milk"},
  {q:"40g",n:"GF chocolate protein powder",gf:true},
  {q:"2 tbsp",n:"raw cacao powder"},
  {q:"2 tsp",n:"maple syrup"},
  {q:"100g",n:"coconut yoghurt"},
  {q:"1",n:"banana, sliced"},
],
method:[
  "Simmer coconut milk. Stir in oats and cacao; cook 5–8 mins until thick.",
  "Remove from heat. Stir in protein powder, maple syrup and yoghurt.",
  "Divide into two bowls. Top with banana slices.",
],
free:false,adaptations:[{orig:"Regular oats + whey protein + dairy milk",swap:"Certified GF oats + GF vegan protein + coconut milk"}],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin ✓ or Nuzest ✓"],
tags:["batch","quick"],note:""},

{id:"paella",name:"Paella",cycle:3,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"1",n:"white onion, finely chopped"},
  {q:"1",n:"red pepper, sliced"},
  {q:"130g",n:"chestnut mushrooms, thickly sliced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"1 tsp",n:"smoked paprika"},
  {q:"130g",n:"paella rice (or risotto rice)"},
  {q:"2",n:"GF vegetable stock cubes",gf:true},
  {q:"400ml",n:"boiling water"},
  {q:"190g",n:"frozen edamame beans"},
  {q:"small bunch",n:"parsley"},
  {q:"1",n:"lemon, cut into wedges"},
],
method:[
  "Fry onion and pepper 5 mins. Add mushrooms, garlic and paprika; fry 1 min.",
  "Stir in rice and crumbled stock cubes. Pour over water; stir briefly.",
  "Simmer gently 15 mins without stirring.",
  "Scatter edamame over top; cook 2 mins. Rest 5 mins. Serve with parsley and lemon.",
],
free:false,adaptations:[],
gfCheck:["Stock cubes — Kallo GF or Marigold GF"],
tags:["batch","family"],note:"Only the stock cube needs a GF label check. Makes 2 portions."},

{id:"bananaDatCinnamonSmoothie",name:"Banana, Date & Cinnamon Smoothie",cycle:3,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"4",n:"bananas (2 fresh, 2 frozen)"},
  {q:"8",n:"Medjool dates, pitted"},
  {q:"600ml",n:"full-fat coconut milk"},
  {q:"2 tsp",n:"ground cinnamon"},
  {q:"2 tbsp",n:"tahini"},
  {q:"handful",n:"ice"},
],
method:["Blend all ingredients until smooth and creamy. Pour into two glasses."],
free:true,adaptations:[],gfCheck:[],
tags:["quick","otg"],note:"Naturally sweet — no added sugar needed. Makes 2 portions."},

{id:"avocadoBerrySmoothie",name:"Avocado & Berry Smoothie",cycle:3,mealTypes:["breakfast"],prep:5,cook:0,
ingredients:[
  {q:"110g",n:"avocado"},
  {q:"60g",n:"GF vegan vanilla protein powder",gf:true},
  {q:"380ml",n:"full-fat coconut milk"},
  {q:"120g",n:"blueberries"},
  {q:"100g",n:"raspberries"},
  {q:"40g",n:"flaked almonds"},
  {q:"handful",n:"ice"},
],
method:["Blend everything until smooth. Pour into two glasses or jars."],
free:false,adaptations:[{orig:"Almond milk + Greek yoghurt",swap:"Coconut milk — avocado provides creaminess"}],
gfCheck:["Protein powder — Pulsin or Nuzest, labelled GF"],
tags:["quick","otg"],note:"Makes 2 portions."},

{id:"beanTacos",name:"Bean Tacos with Roasted Chilli Salsa",cycle:3,mealTypes:["refuel"],prep:15,cook:20,
ingredients:[
  {q:"2",n:"tomatoes"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"1",n:"red chilli, deseeded"},
  {q:"2 cloves",n:"garlic, unpeeled"},
  {q:"large bunch",n:"coriander, chopped"},
  {q:"juice of 2",n:"limes"},
  {q:"390g",n:"tinned mixed beans, drained"},
  {q:"1 tbsp",n:"chipotle paste",gf:true},
  {q:"1 tsp",n:"ground cumin"},
  {q:"4 small",n:"GF corn tortillas",gf:true},
  {q:"1",n:"avocado, sliced"},
],
method:[
  "Preheat oven to 220°C. Roast tomatoes, onion, chilli and garlic 10 mins until blistered.",
  "Peel garlic; blend with roasted veg, half the coriander and half the lime juice. Season.",
  "Simmer beans with chipotle, cumin and a splash of water 5 mins. Roughly mash half the beans; stir in remaining lime.",
  "Warm tortillas under grill. Spread with beans, top with salsa, avocado and remaining coriander.",
],
free:false,adaptations:[
  {orig:"Feta",swap:"Avocado for creaminess"},
  {orig:"Flour tortillas",swap:"GF corn tortillas — Old El Paso GF or Mission GF"},
],
gfCheck:["Corn tortillas — check GF labelling","Chipotle paste — check label"],
tags:["family"],note:"Bright, fresh post-workout refuel. Makes 2 portions."},

{id:"chickpeaPancakes",name:"Chickpea Pancakes with Avocado",cycle:3,mealTypes:["refuel"],prep:10,cook:15,
ingredients:[
  {q:"160g",n:"gram flour (chickpea flour)"},
  {q:"1 tsp",n:"turmeric"},
  {q:"large bunch",n:"flat-leaf parsley, chopped"},
  {q:"80g",n:"spring onions, finely chopped"},
  {q:"350ml",n:"water (adjust to consistency)"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"ripe avocado, sliced"},
  {q:"juice of 2",n:"limes"},
  {q:"80g",n:"cherry tomatoes, halved"},
  {q:"pinch",n:"smoked paprika"},
],
method:[
  "Whisk gram flour, turmeric, parsley and spring onions. Gradually add water to a smooth batter (double cream consistency). Season.",
  "Heat oil in a large frying pan over high heat. Pour batter to coat base; fry 2 mins each side until golden. Repeat.",
  "Stack pancakes and top with avocado, lime juice, tomatoes and paprika.",
],
free:true,adaptations:[{orig:"Feta",swap:"Omitted — avocado provides creaminess"}],gfCheck:[],
tags:["family"],note:"Gram flour is naturally GF, DF and EF. Makes 2 portions."},

{id:"chickpeaAubergineCurry",name:"Chickpea & Aubergine Curry",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"1",n:"aubergine, diced"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"40g",n:"fresh ginger, grated"},
  {q:"1 tsp each",n:"chilli powder, cumin, garam masala, turmeric"},
  {q:"60g",n:"almond butter"},
  {q:"260g",n:"tinned chickpeas, drained"},
  {q:"small bunch",n:"coriander"},
],
method:[
  "Microwave diced aubergine covered 5–6 mins until soft.",
  "Fry onion, garlic and ginger in coconut oil 2 mins. Add spices 1 min.",
  "Stir in almond butter with 200ml water; simmer 5 mins.",
  "Add chickpeas and aubergine; cook 5 mins. Season and top with coriander.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","family"],note:"100% naturally GF, DF and EF. Makes 2 portions."},

{id:"coconutDaal",name:"Coconut Daal with Chickpeas",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:25,
ingredients:[
  {q:"160g",n:"dried red lentils, rinsed"},
  {q:"½ tsp",n:"turmeric"},
  {q:"600ml",n:"boiling water"},
  {q:"190g",n:"tinned chickpeas, drained"},
  {q:"180ml",n:"tinned coconut milk"},
  {q:"1 tbsp",n:"coconut oil"},
  {q:"1 large",n:"red onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"30g",n:"fresh ginger, grated"},
  {q:"2",n:"green chillies, finely chopped"},
  {q:"2 tsp",n:"mustard seeds"},
  {q:"2 tsp",n:"ground cumin"},
  {q:"½ tsp",n:"chilli powder"},
  {q:"large bunch",n:"coriander, chopped"},
],
method:[
  "Simmer lentils with turmeric in water 10 mins. Add chickpeas and coconut milk; simmer 10 mins more until lentils are soft.",
  "Meanwhile fry onion in coconut oil 5 mins until caramelised. Add garlic, ginger and chilli 2 mins.",
  "Add spices; fry 1 min. Tip tarka into the lentil pan. Season with salt and stir through coriander.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","family"],note:"100% naturally GF, DF and EF. Makes 2 portions."},

{id:"proteinPowerBowl",name:"Protein Power Bowl",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:0,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"2 tsp",n:"red wine vinegar"},
  {q:"80g",n:"cooked quinoa"},
  {q:"110g",n:"cherry tomatoes, halved"},
  {q:"110g",n:"baby leaf spinach"},
  {q:"70g",n:"avocado, sliced"},
  {q:"80g",n:"smoked or firm tofu, diced"},
  {q:"40g",n:"pumpkin seeds"},
],
method:[
  "Whisk oil, vinegar and seasoning. Toss quinoa, tomatoes and spinach in dressing.",
  "Divide into two bowls. Top with avocado, tofu and pumpkin seeds.",
],
free:true,adaptations:[],gfCheck:[],
tags:["quick","otg"],note:"100% naturally GF, DF and EF. Makes 2 portions."},

{id:"roastedSquashQuinoaSalad",name:"Roasted Squash & Quinoa Salad",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"310g",n:"butternut squash, sliced"},
  {q:"1",n:"red pepper, roughly chopped"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"130g",n:"cooked quinoa (or 65g dry)"},
  {q:"1 tbsp",n:"red wine vinegar"},
  {q:"50g",n:"pumpkin seeds"},
  {q:"2 handfuls",n:"mixed salad leaves"},
],
method:[
  "Preheat oven to 220°C. Lay squash and pepper on a tray, drizzle with oil, season. Roast 15–20 mins until golden.",
  "Combine roasted veg with quinoa, vinegar, seeds and salad leaves. Toss and serve.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","otg"],note:"100% naturally GF, DF and EF. Makes 2 portions."},

{id:"spicyNoodleSalad",name:"Spicy Noodle Salad with Edamame",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:5,
ingredients:[
  {q:"4 tsp",n:"tamari (GF soy sauce)",gf:true},
  {q:"4 tsp",n:"sesame oil"},
  {q:"1 tsp",n:"brown sugar"},
  {q:"zest and juice of 2",n:"limes"},
  {q:"2",n:"red chillies, finely chopped"},
  {q:"190g",n:"edamame beans (soya beans)"},
  {q:"12",n:"radishes, quartered"},
  {q:"½",n:"cucumber, thinly sliced"},
  {q:"110g",n:"smoked tofu, diced"},
  {q:"80g",n:"rice noodles, cooked per packet"},
  {q:"40g",n:"roasted cashews, crushed"},
  {q:"large bunch",n:"coriander, chopped"},
],
method:[
  "Whisk tamari, sesame oil, sugar, lime zest and juice and chilli in a large bowl.",
  "Add all remaining ingredients and toss together to combine.",
],
free:false,adaptations:[{orig:"Light soy sauce",swap:"Tamari — certified GF"}],
gfCheck:["Tamari — Kikkoman GF or Clearspring Tamari"],
tags:["quick","otg"],note:"No cooking needed if using pre-cooked rice noodles. Makes 2 portions."},

{id:"butternutSquashCoconutSoup",name:"Butternut Squash & Coconut Soup",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"2 tsp",n:"coconut oil"},
  {q:"310g",n:"butternut squash, diced"},
  {q:"1",n:"red onion, sliced"},
  {q:"1",n:"red chilli, sliced"},
  {q:"1 tsp",n:"ground cumin"},
  {q:"1 tsp",n:"turmeric"},
  {q:"180ml",n:"tinned coconut milk"},
  {q:"380ml",n:"water"},
  {q:"20g",n:"unflavoured protein powder",gf:true},
  {q:"juice of 1",n:"lime"},
  {q:"40g",n:"roasted peanuts, crushed"},
  {q:"large bunch",n:"coriander, chopped"},
],
method:[
  "Fry squash in coconut oil 3–4 mins until slightly coloured. Add onion and chilli 2 mins.",
  "Add spices; fry 1 min. Pour in coconut milk, water and protein powder. Simmer 7–8 mins.",
  "Blend until smooth. Stir in lime juice. Serve topped with peanuts and coriander.",
],
free:true,adaptations:[],gfCheck:[],
tags:["batch","family"],note:"Naturally GF, DF and EF. Makes 2 portions."},

{id:"chargrillTofuMisoAubergine",name:"Chargrilled Tofu with Miso Aubergine",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:20,
ingredients:[
  {q:"2 medium",n:"aubergines"},
  {q:"1 tsp each",n:"coconut oil and sesame oil"},
  {q:"20g",n:"fresh ginger, grated"},
  {q:"60g",n:"white miso paste",gf:true},
  {q:"280g",n:"smoked tofu, diced"},
  {q:"30g",n:"peanut butter"},
  {q:"1 tbsp",n:"sriracha chilli sauce"},
  {q:"juice of 2",n:"limes"},
  {q:"40g",n:"spring onions, finely chopped"},
],
method:[
  "Score aubergine flesh in a criss-cross pattern; microwave covered 5–6 mins until softened.",
  "Mix oils, ginger and miso into a paste. Rub over cut halves; grill 5 mins until golden.",
  "Griddle tofu 2–3 mins each side until lightly charred.",
  "Whisk peanut butter, sriracha and lime juice. Serve with aubergine, tofu and spring onions.",
],
free:false,adaptations:[{orig:"Miso paste (may contain gluten)",swap:"Clearspring Organic White Miso — GF certified"}],
gfCheck:["White miso — must be GF certified (Clearspring Organic ✓)"],
tags:["quick","family"],note:"Umami-rich Japanese-inspired dish. Makes 2 portions."},

{id:"spicyPeanutNoodles",name:"Spicy Peanut Noodles",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:10,
ingredients:[
  {q:"2 tsp",n:"coconut oil"},
  {q:"6",n:"spring onions, sliced"},
  {q:"130g",n:"sugar snap peas, sliced"},
  {q:"190g",n:"smoked tofu, diced"},
  {q:"140g",n:"rice noodles, cooked"},
  {q:"40g",n:"peanut butter"},
  {q:"4 tsp",n:"tamari (GF soy sauce)",gf:true},
  {q:"juice of 1",n:"lime"},
  {q:"½ tsp",n:"chilli flakes"},
  {q:"10g",n:"roasted peanuts, crushed"},
  {q:"large bunch",n:"coriander, chopped"},
],
method:[
  "Heat oil in wok. Fry spring onions, sugar snap peas and tofu 2–3 mins.",
  "Add cooked noodles; stir-fry 2 mins to warm through.",
  "Whisk peanut butter, tamari, lime juice, chilli and a splash of water. Pour into wok and toss.",
  "Serve topped with peanuts and coriander.",
],
free:false,adaptations:[
  {orig:"Udon noodles (wheat)",swap:"Rice noodles — naturally GF"},
  {orig:"Light soy sauce",swap:"Tamari — certified GF"},
],
gfCheck:["Tamari — Kikkoman GF or Clearspring"],
tags:["quick","family"],note:"Quick weeknight dinner. Makes 2 portions."},

{id:"chilliSinCarne",name:"Chilli Sin Carne",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:30,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"200g",n:"dried green lentils"},
  {q:"20g",n:"tomato purée"},
  {q:"1 tsp each",n:"cumin, chilli powder, cinnamon"},
  {q:"190g",n:"tinned chopped tomatoes"},
  {q:"120g",n:"tinned kidney beans, drained"},
  {q:"80ml",n:"coconut cream"},
  {q:"juice of 1",n:"lime"},
  {q:"small bunch",n:"coriander"},
],
method:[
  "Fry onion and garlic 5 mins. Add lentils, purée and spices; fry 1 min.",
  "Add tomatoes and 300ml water. Simmer 20 mins until lentils tender.",
  "Add kidney beans; cook 5 mins. Season. Drizzle coconut cream; squeeze lime.",
],
free:false,adaptations:[
  {orig:"Quorn mince",swap:"Green lentils — Quorn contains egg white and wheat"},
  {orig:"Cheddar + soured cream",swap:"Coconut cream + lime juice"},
],
gfCheck:[],
tags:["batch","family"],note:"Lentils replace Quorn throughout this plan. Makes 2 portions."},

{id:"gfMinestrone",name:"GF Minestrone",cycle:3,mealTypes:["refuel"],prep:10,cook:25,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"onion, diced"},
  {q:"2",n:"carrots, diced"},
  {q:"2 sticks",n:"celery, diced"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"2",n:"GF stock cubes in 800ml water",gf:true},
  {q:"400g",n:"tinned chopped tomatoes"},
  {q:"240g",n:"tinned cannellini beans, drained"},
  {q:"100g",n:"GF small pasta",gf:true},
  {q:"large handful",n:"baby spinach"},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Fry onion, carrot and celery 5 mins. Add garlic and purée 2 mins.",
  "Pour in stock and tomatoes. Simmer 10 mins.",
  "Add beans and GF pasta; cook 8–10 mins until pasta is tender.",
  "Stir in spinach and nutritional yeast. Season well.",
],
free:false,adaptations:[
  {orig:"Regular pasta",swap:"GF pasta — Doves Farm or Rizopia"},
  {orig:"Parmesan",swap:"Nutritional yeast"},
],
gfCheck:["GF pasta — Doves Farm ✓, Rizopia ✓","Stock cubes — Kallo GF ✓"],
tags:["batch","family"],note:"Carb-rich refuel. Makes 2 portions."},

{id:"appleAndCinnamonBars",name:"Apple & Cinnamon Breakfast Bars",cycle:3,mealTypes:["breakfast","refuel"],prep:10,cook:30,
ingredients:[
  {q:"195g",n:"certified GF rolled oats",gf:true},
  {q:"70g",n:"coconut flour"},
  {q:"85g",n:"GF vanilla protein powder",gf:true},
  {q:"55g",n:"ground flaxseed"},
  {q:"2 tbsp",n:"ground cinnamon"},
  {q:"235g",n:"pitted Medjool dates (approx 14), chopped"},
  {q:"215g",n:"unsweetened apple sauce"},
  {q:"90g",n:"almond butter"},
  {q:"70g",n:"coconut oil, melted"},
  {q:"75ml",n:"boiling water"},
  {q:"195g",n:"raisins"},
  {q:"2",n:"apples, cored and grated"},
],
method:[
  "Preheat oven to 180°C. Line a 20×30cm tin with greaseproof paper.",
  "Combine oats, coconut flour, protein powder, flaxseed and cinnamon in a large bowl.",
  "Blend dates, apple sauce, almond butter, coconut oil and boiling water until a smooth purée.",
  "Pour purée into dry ingredients; stir to combine. Fold in raisins and grated apple.",
  "Spread in lined tin and bake 30 mins until golden. Cool completely before cutting into 9 bars.",
],
free:true,adaptations:[{orig:"Regular oats",swap:"Certified GF rolled oats (only change needed)"}],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin or Nuzest GF"],
tags:["batch","otg"],note:"Naturally GF, DF and EF. Makes 9 bars. Stores 5 days or freeze."},

{id:"spicyAubergineSpaghetti",name:"Spicy Aubergine Spaghetti",cycle:3,mealTypes:["refuel"],prep:5,cook:20,
ingredients:[
  {q:"2 medium",n:"aubergines (approx 400g), diced"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"4 cloves",n:"garlic, crushed"},
  {q:"1",n:"red chilli, deseeded and finely chopped"},
  {q:"4 tsp",n:"tomato purée"},
  {q:"280g",n:"tinned chopped tomatoes"},
  {q:"1 tbsp",n:"red wine vinegar"},
  {q:"140g",n:"GF spaghetti",gf:true},
  {q:"small bunch",n:"basil, leaves torn"},
],
method:[
  "Microwave diced aubergine covered 5–6 mins until softened.",
  "Heat oil; fry garlic and chilli 2 mins. Add tomato purée 1 min. Add tomatoes, vinegar and aubergine; simmer covered 5 mins.",
  "Cook GF spaghetti per packet. Drain, reserving pasta water.",
  "Toss pasta into sauce; loosen with pasta water. Stir through basil and season.",
],
free:false,adaptations:[
  {orig:"Wheat spaghetti",swap:"GF spaghetti — Barilla GF or Doves Farm"},
  {orig:"Ricotta",swap:"Omitted — sauce is rich without it"},
],
gfCheck:["GF pasta — Barilla GF ✓, Doves Farm ✓"],
tags:["quick","batch"],note:"Carb-rich post-workout refuel. Makes 2 portions."},

{id:"meanGreenPasta",name:"Mean Green Pasta",cycle:3,mealTypes:["refuel"],prep:5,cook:15,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"white onion, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"230g",n:"frozen peas"},
  {q:"110g",n:"baby leaf spinach"},
  {q:"small bunch",n:"basil"},
  {q:"150g",n:"GF tagliatelle or wide GF pasta",gf:true},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Heat oil; fry onion and garlic gently 3–4 mins. Add peas; fry 1 min. Pour over boiling water to cover; simmer 3–4 mins.",
  "Blend pea mixture with spinach and basil to a rough vibrant-green sauce.",
  "Cook GF pasta per packet. Drain. Toss with green sauce and nutritional yeast. Season and serve.",
],
free:false,adaptations:[
  {orig:"Wheat pappardelle/tagliatelle",swap:"GF pasta — Doves Farm or Rizopia"},
  {orig:"Hard cheese",swap:"Nutritional yeast"},
],
gfCheck:["GF pasta — Doves Farm ✓, Rizopia ✓"],
tags:["quick","family"],note:"Bright, vibrant carb refuel with hidden greens. Makes 2 portions."},

{id:"chiaAndAlmondBowl",name:"Chia & Almond Bowl",cycle:3,mealTypes:["breakfast"],prep:15,cook:10,
ingredients:[
  {q:"190ml",n:"full-fat tinned coconut milk"},
  {q:"40g",n:"certified GF rolled oats",gf:true},
  {q:"40g",n:"chia seeds"},
  {q:"50g",n:"GF vanilla protein powder",gf:true},
  {q:"2 tbsp",n:"coconut yoghurt"},
  {q:"240g",n:"plums (approx 4), stoned and cut into wedges"},
  {q:"4 tsp",n:"maple syrup or honey"},
  {q:"1 tsp",n:"mixed spice"},
  {q:"20g",n:"toasted flaked almonds"},
],
method:[
  "Stir together coconut milk, oats, chia seeds, protein powder and coconut yoghurt. Set aside at least 15 mins (or overnight).",
  "Simmer plums with sweetener, mixed spice and a splash of water 8–10 mins until softened. Cool.",
  "Divide coconut-chia mixture between two bowls. Spoon over plum compote; top with flaked almonds.",
],
free:false,adaptations:[
  {orig:"Regular oats",swap:"Certified GF rolled oats"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:["Oats — certified GF (Nairn's)","Protein powder — Pulsin or Nuzest GF"],
tags:["batch"],note:"Prep the night before; loosen with a splash of coconut milk if too thick. Makes 2 portions."},

{id:"broccoliLentilSoup",name:"Broccoli & Lentil Soup",cycle:3,mealTypes:["lunch","dinner"],prep:5,cook:25,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"200g",n:"dried red lentils"},
  {q:"190g",n:"broccoli florets"},
  {q:"530ml",n:"full-fat tinned coconut milk"},
  {q:"8 tbsp",n:"nutritional yeast"},
  {q:"4 tbsp",n:"coconut yoghurt (to serve)"},
],
method:[
  "Heat oil; fry garlic 1 min. Stir in lentils; pour over boiling water to cover by 2cm. Simmer 15 mins.",
  "Add broccoli and coconut milk; simmer 5 mins until broccoli is soft.",
  "Remove from heat; blend until smooth. Stir in nutritional yeast; season well.",
  "Ladle into bowls; swirl over coconut yoghurt.",
],
free:true,adaptations:[
  {orig:"Skimmed milk",swap:"Full-fat tinned coconut milk"},
  {orig:"Mature cheddar",swap:"Nutritional yeast"},
  {orig:"Greek yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:[],
tags:["batch","otg"],note:"Naturally GF, DF and EF. Freezes well. Makes 2 portions."},

{id:"creamyMushroomAsparagus",name:"Creamy Mushroom & Asparagus Pasta",cycle:3,mealTypes:["lunch","dinner"],prep:5,cook:20,
ingredients:[
  {q:"60g",n:"unsalted cashews"},
  {q:"140g",n:"GF wide pasta or tagliatelle",gf:true},
  {q:"190g",n:"asparagus, sliced"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"190g",n:"chestnut mushrooms, thickly sliced"},
  {q:"150g",n:"firm tofu, drained"},
  {q:"4 tbsp",n:"nutritional yeast"},
],
method:[
  "Soak cashews 15 mins in just-boiling water; blend with a splash of soaking liquid until smooth.",
  "Cook GF pasta per packet; add asparagus for final 1 min. Drain, reserving pasta water.",
  "Heat oil; fry garlic 1 min. Add mushrooms; fry 3–4 mins until golden.",
  "Blend tofu, cashew cream, nutritional yeast and a splash of pasta water until creamy.",
  "Pour sauce into mushroom pan; add pasta and asparagus; toss together, loosening with pasta water. Season.",
],
free:false,adaptations:[
  {orig:"Wheat pappardelle",swap:"GF wide pasta (Doves Farm ✓, Rizopia ✓)"},
  {orig:"Low-fat crème fraîche",swap:"Cashew cream (60g cashews soaked + blended)"},
  {orig:"Hard cheese",swap:"Nutritional yeast"},
],
gfCheck:["GF pasta — Doves Farm ✓, Rizopia ✓"],
tags:["quick"],note:"Rich and satisfying general meal. Makes 2 portions."},

{id:"stuffedPeppers",name:"Stuffed Peppers with Quinoa",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:25,
ingredients:[
  {q:"4 small",n:"red peppers"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"red onion, finely chopped"},
  {q:"2 small",n:"courgettes, grated"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"130g",n:"cooked quinoa (or 65g dry)"},
  {q:"small bunch",n:"flat-leaf parsley, chopped"},
  {q:"40g",n:"toasted pine nuts"},
  {q:"110g",n:"coconut yoghurt"},
  {q:"small bunch",n:"mint, chopped"},
],
method:[
  "Preheat oven to 220°C. Cut tops off peppers; scoop out seeds. Roast on a tray 10 mins.",
  "Heat oil; fry onion, courgette and garlic 5 mins until soft. Combine with quinoa and parsley; season.",
  "Spoon filling into peppers; scatter pine nuts on top. Return to oven 10–15 mins until peppers are soft.",
  "Mix coconut yoghurt and mint. Serve peppers with mint yoghurt and a green salad.",
],
free:true,adaptations:[
  {orig:"Feta",swap:"Toasted pine nuts for texture — quinoa provides protein"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt (CoYo or Koko)"},
],
gfCheck:[],
tags:["family","batch"],note:"Naturally GF, DF and EF. Filling can be prepped ahead. Makes 2 portions."},

// Cycle 3 adapted (7)
{id:"caramelisedAppleFrenchToast",name:"Caramelised Apple French Toast",cycle:3,mealTypes:["refuel"],prep:10,cook:15,
ingredients:[
  {q:"4 tbsp",n:"ground flaxseed"},
  {q:"180ml",n:"water (for flax eggs)"},
  {q:"4 tbsp",n:"GF oat milk or coconut milk",gf:true},
  {q:"pinch",n:"salt"},
  {q:"pinch",n:"ground cinnamon"},
  {q:"2",n:"GF English muffins, split (4 halves)",gf:true},
  {q:"1 tsp",n:"brown sugar"},
  {q:"20g",n:"honey"},
  {q:"1",n:"apple, peeled, cored and cut into wedges"},
  {q:"2 tsp",n:"coconut oil or vegan butter"},
  {q:"60g",n:"coconut yoghurt"},
  {q:"20g",n:"toasted flaked almonds"},
],
method:[
  "Mix ground flaxseed with water and oat milk; rest 5–10 mins. Add cinnamon and salt; soak muffin halves in the mixture 5 mins.",
  "Heat sugar and honey in a frying pan; add apple wedges and cook 5 mins over medium heat, turning until golden and caramelised. Remove.",
  "Melt coconut oil in a non-stick pan; fry soaked muffin halves 2 mins each side until golden.",
  "Arrange on plates, spoon caramelised apple over; top with coconut yoghurt and flaked almonds.",
],
free:false,adaptations:[
  {orig:"2 eggs",swap:"Flax egg soak (ground flaxseed + water + oat milk)"},
  {orig:"Skimmed milk",swap:"GF oat milk or coconut milk"},
  {orig:"Wholemeal wheat muffin",swap:"GF English muffin (Genius GF or similar)"},
  {orig:"Butter",swap:"Coconut oil or vegan butter"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:["GF muffins — Genius GF ✓ or similar (check label)","Oat milk — GF certified (if using)"],
tags:["quick","family"],note:"Cut muffins the night before and leave to dry out — stale muffins soak better. Makes 2 portions."},

{id:"potatoPancakesTomatoes",name:"Potato Pancakes with Roasted Tomatoes",cycle:3,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"320g",n:"potatoes, peeled and cut into chunks"},
  {q:"150g",n:"cherry tomatoes"},
  {q:"salt and pepper",n:"to season"},
  {q:"80g",n:"GF plain flour",gf:true},
  {q:"30g",n:"GF unflavoured protein powder",gf:true},
  {q:"2 tbsp",n:"ground flaxseed"},
  {q:"6 tbsp",n:"water (for flax eggs)"},
  {q:"1 tbsp",n:"vegan butter or coconut oil"},
],
method:[
  "Preheat oven to 200°C. Boil potatoes 8–10 mins until tender; drain and leave to steam dry completely.",
  "Roast cherry tomatoes on a baking tray with salt and pepper 10 mins until softened.",
  "Mix ground flaxseed with water; rest 5 mins. Mash potatoes; stir in GF flour, protein powder, flax eggs and plenty of seasoning. Shape into a disc about 1cm thick; cut into quarters.",
  "Heat vegan butter in a non-stick pan; fry potato pancakes 2 mins each side until golden. Serve with roasted tomatoes.",
],
free:false,adaptations:[
  {orig:"Plain wheat flour",swap:"GF plain flour (Doves Farm)"},
  {orig:"1 medium egg",swap:"Flax egg (1 tbsp ground flaxseed + 3 tbsp water)"},
  {orig:"Butter",swap:"Vegan butter (Naturli or Flora Plant)"},
],
gfCheck:["GF plain flour — Doves Farm ✓","Protein powder — Pulsin GF ✓ (unflavoured)"],
tags:["batch","otg"],note:"Drain and cool potatoes fully — wet mash makes sticky, unworkable dough. Makes 2 portions."},

{id:"loadedSweetPotatoSkins",name:"Loaded Sweet Potato Skins with Tofu Scramble",cycle:3,mealTypes:["refuel"],prep:10,cook:20,
ingredients:[
  {q:"2 large",n:"sweet potatoes (approx 520g total)"},
  {q:"1 tbsp",n:"olive oil"},
  {q:"1",n:"red pepper, deseeded and diced"},
  {q:"130g",n:"spring onions, sliced"},
  {q:"130g",n:"cherry tomatoes, quartered"},
  {q:"pinch",n:"chilli flakes"},
  {q:"small bunch",n:"chives, finely chopped"},
  {q:"salt and pepper",n:"to season"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"300g",n:"firm tofu, crumbled"},
  {q:"½ tsp",n:"turmeric"},
  {q:"2 tsp",n:"tamari (GF)",gf:true},
  {q:"1 tsp",n:"olive oil (for tofu)"},
],
method:[
  "Microwave sweet potatoes 8–10 mins until soft. Halve, cool slightly, then scoop flesh into a bowl; bake skins cut-side up 10 mins at 200°C until crisp.",
  "Heat half the oil; fry pepper, spring onions and tomatoes 5 mins. Mix into sweet potato flesh with chilli flakes and chives; season.",
  "Spoon filling into crispy skins; scatter with nutritional yeast and grill 2–3 mins until golden.",
  "Heat remaining oil; fry tofu with turmeric and tamari 3–4 mins until scrambled. Serve alongside skins.",
],
free:false,adaptations:[
  {orig:"2 beaten eggs (scrambled)",swap:"Scrambled tofu (turmeric + tamari)"},
  {orig:"Mature cheddar",swap:"Nutritional yeast"},
],
gfCheck:["Tamari — Kikkoman GF ✓"],
tags:["quick","family"],note:"Makes 2 portions."},

{id:"spicyProteinBurger",name:"Spicy Black Bean Protein Burger",cycle:3,mealTypes:["refuel"],prep:10,cook:15,
ingredients:[
  {q:"290g",n:"tinned black beans or kidney beans, drained — reserve brine"},
  {q:"20g",n:"GF unflavoured protein powder",gf:true},
  {q:"1 tbsp",n:"chipotle paste",gf:true},
  {q:"60g",n:"gram flour (chickpea flour)"},
  {q:"4 tbsp",n:"aquafaba (brine from tin) or 2 flax eggs"},
  {q:"small bunch",n:"coriander, chopped"},
  {q:"salt and pepper",n:"to season"},
  {q:"4 tsp",n:"olive oil"},
  {q:"2",n:"GF burger buns, split and toasted",gf:true},
  {q:"60g",n:"vegan mayo",gf:true},
  {q:"4 leaves",n:"baby gem lettuce"},
  {q:"4 slices",n:"white or red onion"},
],
method:[
  "Blend beans, protein powder, chipotle paste, gram flour, aquafaba and coriander to a coarse paste; season. Shape into 2 thick patties.",
  "Heat oil in a frying pan; fry patties 3–4 mins each side until golden and cooked through.",
  "Spread buns with vegan mayo; lay burgers on top and finish with lettuce and onion slices.",
],
free:false,adaptations:[
  {orig:"1 egg white",swap:"Aquafaba (reserved brine from the bean tin — zero waste)"},
  {orig:"Wheat burger bun",swap:"GF burger bun (Warburtons GF or Genius)"},
  {orig:"Light mayonnaise",swap:"Vegan mayo"},
  {orig:"Unflavoured protein powder",swap:"GF unflavoured protein powder"},
],
gfCheck:["GF burger buns — Warburtons GF ✓ or Genius GF ✓","Chipotle paste — check label","Protein powder — Pulsin GF ✓","Vegan mayo — Hellmann's Vegan ✓"],
tags:["batch","otg"],note:"Refrigerate patties 30 mins if mixture is soft. Makes 2 portions."},

{id:"veggieCaesarSalad",name:"Veggie Caesar Salad",cycle:3,mealTypes:["lunch","dinner"],prep:10,cook:15,
ingredients:[
  {q:"1",n:"GF bagel, torn into chunks",gf:true},
  {q:"110g",n:"coconut yoghurt"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"1 tbsp",n:"extra virgin olive oil"},
  {q:"2 tsp",n:"Dijon mustard"},
  {q:"juice of ½",n:"lemon"},
  {q:"salt and pepper",n:"to season"},
  {q:"12 leaves",n:"baby gem or cos lettuce, torn"},
  {q:"60g",n:"firm tofu, diced"},
  {q:"6",n:"baby carrots, thinly sliced"},
  {q:"12",n:"radishes, thinly sliced"},
],
method:[
  "Preheat oven to 180°C; bake torn bagel pieces 15 mins until crisp. Leave to cool.",
  "Whisk coconut yoghurt, nutritional yeast, olive oil, mustard and lemon juice until smooth; season to taste.",
  "Toss bagel croutons and all remaining ingredients in the dressing to coat.",
],
free:false,adaptations:[
  {orig:"Plain wheat bagel",swap:"GF bagel (Warburtons GF or Genius)"},
  {orig:"Hard cheese (grated)",swap:"Nutritional yeast"},
  {orig:"Greek/natural yoghurt",swap:"Coconut yoghurt"},
],
gfCheck:["GF bagel — Warburtons GF ✓ or Genius GF ✓"],
tags:["quick","otg"],note:"Dressing keeps 3 days in the fridge — make double and save. Makes 2 portions."},

{id:"lowCarbLasagne",name:"Low-carb Lentil Lasagne",cycle:3,mealTypes:["lunch","dinner"],prep:20,cook:60,
ingredients:[
  {q:"1 tbsp",n:"olive oil"},
  {q:"2",n:"onions, finely chopped"},
  {q:"2 cloves",n:"garlic, crushed"},
  {q:"2×400g tins",n:"green lentils, drained"},
  {q:"30g",n:"tomato purée"},
  {q:"380g",n:"tinned chopped tomatoes"},
  {q:"salt and pepper",n:"to season"},
  {q:"2 tbsp",n:"vegan butter"},
  {q:"30g",n:"GF plain flour",gf:true},
  {q:"380ml",n:"GF oat milk or full-fat coconut milk",gf:true},
  {q:"475g",n:"butternut squash (thick neck end), very thinly sliced"},
  {q:"8 tbsp",n:"nutritional yeast"},
],
method:[
  "Heat oil; cook onions and garlic 5 mins. Add lentils; fry 2 mins. Stir in tomato purée 1 min; pour in tomatoes and a splash of water. Simmer 15 mins; season.",
  "Make white sauce: melt vegan butter, whisk in GF flour, then gradually whisk in milk. Cook over medium heat until thickened; stir in half the nutritional yeast.",
  "Preheat oven to 180°C. Layer lentil sauce, white sauce and squash sheets; finish with white sauce and scatter over remaining nutritional yeast.",
  "Bake 60 mins until squash is tender. Rest 10 mins before serving.",
],
free:false,adaptations:[
  {orig:"665g Quorn mince",swap:"2×400g tins green lentils — Quorn contains egg white and wheat"},
  {orig:"Plain wheat flour (white sauce)",swap:"GF plain flour (Doves Farm)"},
  {orig:"Butter",swap:"Vegan butter (Naturli or Flora Plant)"},
  {orig:"Skimmed milk",swap:"GF oat milk or full-fat coconut milk"},
  {orig:"Mature cheddar",swap:"Nutritional yeast"},
],
gfCheck:["GF plain flour — Doves Farm ✓","Oat milk — GF certified (if using)"],
tags:["batch","family"],note:"Makes 4 portions. Chill overnight before slicing; freeze individual portions."},

{id:"sausageLentilStew",name:"Plant Sausage & Lentil Stew",cycle:3,mealTypes:["lunch","dinner"],prep:5,cook:20,
ingredients:[
  {q:"2 tsp",n:"olive oil"},
  {q:"4",n:"Vivera Plant Sausages (GF, DF, EF)",gf:true},
  {q:"1",n:"onion, finely chopped"},
  {q:"2",n:"carrots, finely chopped"},
  {q:"1",n:"GF vegetable stock cube",gf:true},
  {q:"170g",n:"cooked lentils"},
  {q:"2 tsp",n:"grain mustard or Dijon mustard"},
  {q:"4 tbsp",n:"nutritional yeast"},
  {q:"small bunch",n:"parsley, chopped"},
],
method:[
  "Heat oil in a saucepan over medium heat; fry sausages 7–8 mins until golden all over. Remove; slice thickly.",
  "Fry onion and carrot in the same pan 5 mins until soft; crumble in stock cube. Add lentils and just enough boiling water to cover; simmer 5 mins.",
  "Return sliced sausages to pan; stir to combine. Remove from heat; stir in mustard, nutritional yeast and parsley.",
],
free:false,adaptations:[
  {orig:"2 Quorn sausages",swap:"Vivera Plant Sausages or Linda McCartney GF sausages — Quorn contains egg and wheat"},
  {orig:"Hard cheese (grated)",swap:"Nutritional yeast"},
  {orig:"Vegetable stock cube",swap:"GF vegetable stock cube (Kallo)"},
],
gfCheck:["Vivera Plant Sausages — check GF label (currently GF ✓)","GF stock cube — Kallo GF ✓"],
tags:["quick","batch"],note:"Ready-cooked lentils are fine; cook from dried in 25 mins if preferred. Makes 2 portions."},
]
